const car = {
  carName: "Magotan GTE",
  carInfo: [
    {
      model: "豪华型",
      price: "253900",
      paramList: [
        {
          name: "技术参数",
          list: [
            { key: "长/宽/高[mm]", value: "4865 / 1832 / 1469" },
            { key: "轴距[mm]", value: "2871" },
            { key: "行李箱容积[L]", value: "457" },
            { key: "油箱容积[L]", value: "50" },
            { key: "发动机排量[L]", value: "1.395" },
            {
              key: "发动机型式",
              value:
                "涡轮增压/直列四缸16气阀电控燃油缸内直接喷射Turbo Charging Inline 4-cylinder 16V TSI Engine",
            },
            { key: "发动机最大输出功率[kW/rpm]", value: "110/5000-6000" },
            { key: "发动机最大输出扭矩[Nm/rpm]", value: "250/1750-3000" },
            { key: "电动机峰值功率[kW]", value: "85" },
            { key: "电动机峰值扭矩[Nm]", value: "330" },
            { key: "系统最大功率[kW/rpm]", value: "155" },
            { key: "系统最大扭矩[Nm]", value: "400" },
            {
              key: "排放",
              value: "国六排放标准National stage VI emission standard",
            },
            { key: "变速箱型式", value: "DQ400e 6挡湿式DSG®双离合手自一体" },
            { key: "驱动型式", value: "前轮驱动 FWD" },
            {
              key: "制动系统",
              value:
                "前通风制动盘/后实心制动盘 Ventilated disc break front and solid rear",
            },
            {
              key: "悬架系统[前/后]",
              value:
                "优化麦弗逊独立悬架/升级柔性后轴多连杆独立悬架 Optimized MacPherson Suspension front/muti link independent Suspension",
            },
            { key: "转向系统", value: "电动随速助力转向 EPS" },
            { key: "电池系统额定能量[Ah]", value: "37" },
            { key: "能量密度[Wh/kg]", value: "104" },
            { key: "工信部纯电续航里程[km]", value: "56" },
            { key: "整备质量[kg]", value: "1750" },
            { key: "最高车速[km/h]", value: "200" },
            { key: "0-100km/h加速时间[s]", value: "7.7" },
            { key: "90km/h等速油耗[L/100km]", value: "5.3" },
            { key: "综合油耗[L/100km]", value: "1.8" },
            { key: "综合耗电量[kW·h/100km]", value: "16.5" },
          ],
        },
        {
          name: "外观",
          list: [
            {
              key: "超大全景天窗（滑动 / 倾斜双模开启，防夹功能）",
              value: "●",
            },
            { key: "电动天窗遮阳帘", value: "●" },
            { key: "凌犀远近光一体式高级LED透镜前大灯", value: "●" },
            {
              key: "凌犀高级全LED矩阵式Matrix透镜前大灯（带AFS大灯随动转向、流水式转向灯）",
              value: "○1",
            },
            { key: "C 型LED日间行车灯", value: "●" },
            { key: "凌动全LED尾灯（带流水式动态转向）", value: "●" },
            {
              key: "凌动全LED尾灯（带流水式动态转向及动态位置功能）",
              value: "-",
            },
            { key: "外饰氛围灯(门把手、侧面车型标识）", value: "●" },
            { key: "外后视镜迎宾照地灯", value: "●" },
            { key: "后排深色防紫外线隐私玻璃", value: "-" },
            { key: "17英寸NOCTIS铝合金轮毂", value: "●" },
            { key: "18英寸TOSCANA铝合金轮毂", value: "-" },
            { key: "补胎套装", value: "●" },
            { key: "内饰", value: "" },
            { key: "三幅真皮方向盘", value: "-" },
            { key: "真皮多功能方向盘", value: "●" },
            { key: "真铝换挡手柄", value: "" },
            { key: "Vienna打孔真皮座椅", value: "●" },
            { key: "前排座椅12向电动调节(含4向电动腰托调节)", value: "●" },
            { key: "副驾驶座椅后排电动可调", value: "●" },
            { key: "后排座椅4/6可分折叠", value: "●" },
            { key: "豪华内饰格调氛围灯", value: "●" },
            {
              key: "尊贵内饰格调氛围灯（含30色可变的仪表台及车门装饰条氛围灯等）",
              value: "-",
            },
            { key: "后排出风口", value: "●" },
            { key: '"GTE"标识LED迎宾踏板饰条', value: "●" },
            { key: 'LED光"GTE"徽标金属迎宾踏板', value: "-" },
            { key: "高亮钢琴漆中控台装饰面板", value: "●" },
          ],
        },
        {
          name: "安全/科技",
          list: [
            { key: "激光焊接技术", value: "●" },
            { key: "热成型钢板HSB高强度安全车身", value: "●" },
            { key: "智能在线防盗系统", value: "●" },
            { key: "前排正面双安全气囊", value: "●" },
            { key: "前排侧面双安全气囊", value: "●" },
            { key: "前后贯穿式两侧头部安全气帘", value: "●" },
            { key: "后排侧面双安全气囊", value: "●" },
            { key: "驾驶员膝部安全气囊", value: "●" },
            { key: "前/后8探头泊车雷达", value: "●" },
            {
              key: "PLA 3.0智能自动泊车辅助系统（全方位12探头泊车雷达）",
              value: "-",
            },
            {
              key: "RVC泊车后视影像系统（大众徽标翻盖隐藏式摄像头）",
              value: "●",
            },
            { key: "Area View 360°鸟瞰式全景可视泊车辅助系统", value: "-" },
            { key: "EPB智能电子手刹+Autohold自动驻车", value: "●" },
            {
              key: "全功能ESP车身稳定系统（含ABS, ASR, HBA等多项扩展功能）",
              value: "●",
            },
            { key: "MKB多次碰撞预防系统", value: "●" },
            { key: "RKA智能胎压监测系统", value: "●" },
            { key: "TPMS主动式智能胎压监测系统", value: "○3" },
            { key: "MKE智能疲劳监测系统", value: "●" },
            { key: "GRA定速巡航系统", value: "●" },
            { key: "ACC 3.0高级自适应巡航系统", value: "○4" },
            {
              key: "Front Assist预碰撞安全系统（含CEB城市紧急制动）",
              value: "○4",
            },
            { key: "Pre-Crash 基础与前预碰撞保护系统", value: "-" },
            { key: "儿童座椅固定装置（ISOFIX+Top Tether）", value: "●" },
            { key: "前后排安全带未系提醒", value: "●" },
            { key: "前排电机式预紧限力安全带", value: "-" },
            { key: "自动防眩目内后视镜", value: "●" },
          ],
        },
        {
          name: "功能/豪华",
          list: [
            { key: "发动机启停及能量回收系统", value: "●" },
            { key: "充电预约管理", value: "●" },
            { key: "GTE专属运动模式", value: "●" },
            { key: "大灯感光自动开启", value: "●" },
            { key: "前大灯离回家功能", value: "●" },
            { key: "智能雨量感应无骨雨刷", value: "●" },
            { key: "智能一键启动系统", value: "●" },
            { key: "KESSY智能四门无钥匙进入系统", value: "●" },
            { key: "后备厢脚部感应开启", value: "●" },
            {
              key: "后备厢电动启合功能（带Easy Close舒适关闭功能）",
              value: "●",
            },
            { key: "智能触控式三区自动恒温空调系统", value: "●" },
            { key: "AQS空气质量自动控制系统", value: "●" },
            { key: "CLEAN AIR PM 2.5空气净化系统", value: "●" },
            { key: "外后视镜加热、电动调节功能（集成LED转向灯）", value: "●" },
            { key: "外后视镜电动折叠与锁车自动折叠", value: "●" },
            { key: "副司机侧外后视镜倒车辅助", value: "-" },
            { key: "驾驶员座椅记忆功能带舒适进入", value: "-" },
            { key: "四门一键式防夹电动车窗", value: "●" },
            { key: "后风挡电加热功能", value: "●" },
            { key: "前排座椅加热功能", value: "●" },
            { key: "前排四向调节头枕", value: "●" },
            { key: "后排舒适睡眠头枕", value: "-" },
            { key: "后排USB充电接口", value: "●" },
            { key: "无线充电", value: "●" },
            { key: "顶棚USB充电接口（行车记录仪用）", value: "●" },
            { key: "智能中文显示行车电脑（彩屏）", value: "●" },
            { key: "高分辨率真彩智能中文显示行车电脑", value: "-" },
            { key: "高保真车载音响系统带8扬声器", value: "●" },
            { key: "车载蓝牙系统", value: "●" },
            { key: "全触控屏智能车载导航多媒体系统", value: "●" },
          ],
        },
      ],
    },
    {
      model: "尊贵型",
      price: "268900",
      paramList: [
        {
          name: "技术参数",
          list: [
            { key: "长/宽/高[mm]", value: "4865 / 1832 / 1469" },
            { key: "轴距[mm]", value: "2871" },
            { key: "行李箱容积[L]", value: "457" },
            { key: "油箱容积[L]", value: "50" },
            { key: "发动机排量[L]", value: "1.395" },
            {
              key: "发动机型式",
              value:
                "涡轮增压/直列四缸16气阀电控燃油缸内直接喷射Turbo Charging Inline 4-cylinder 16V TSI Engine",
            },
            { key: "发动机最大输出功率[kW/rpm]", value: "110/5000-6000" },
            { key: "发动机最大输出扭矩[Nm/rpm]", value: "250/1750-3000" },
            { key: "电动机峰值功率[kW]", value: "85" },
            { key: "电动机峰值扭矩[Nm]", value: "330" },
            { key: "系统最大功率[kW/rpm]", value: "155" },
            { key: "系统最大扭矩[Nm]", value: "400" },
            {
              key: "排放",
              value: "国六排放标准National stage VI emission standard",
            },
            { key: "变速箱型式", value: "DQ400e 6挡湿式DSG®双离合手自一体" },
            { key: "驱动型式", value: "前轮驱动 FWD" },
            {
              key: "制动系统",
              value:
                "前通风制动盘/后实心制动盘 Ventilated disc break front and solid rear",
            },
            {
              key: "悬架系统[前/后]",
              value:
                "优化麦弗逊独立悬架/升级柔性后轴多连杆独立悬架 Optimized MacPherson Suspension front/muti link independent Suspension",
            },
            { key: "转向系统", value: "电动随速助力转向 EPS" },
            { key: "电池系统额定能量[Ah]", value: "37" },
            { key: "能量密度[Wh/kg]", value: "104" },
            { key: "工信部纯电续航里程[km]", value: "56" },
            { key: "整备质量[kg]", value: "1750" },
            { key: "最高车速[km/h]", value: "200" },
            { key: "0-100km/h加速时间[s]", value: "7.7" },
            { key: "90km/h等速油耗[L/100km]", value: "5.3" },
            { key: "综合油耗[L/100km]", value: "1.8" },
            { key: "综合耗电量[kW·h/100km]", value: "16.5" },
          ],
        },
        {
          name: "外观",
          list: [
            {
              key: "超大全景天窗（滑动 / 倾斜双模开启，防夹功能）",
              value: "●",
            },
            { key: "电动天窗遮阳帘", value: "●" },
            { key: "凌犀远近光一体式高级LED透镜前大灯", value: "-" },
            {
              key: "凌犀高级全LED矩阵式Matrix透镜前大灯（带AFS大灯随动转向、流水式转向灯）",
              value: "●",
            },
            { key: "C 型LED日间行车灯", value: "●" },
            { key: "凌动全LED尾灯（带流水式动态转向）", value: "-" },
            {
              key: "凌动全LED尾灯（带流水式动态转向及动态位置功能）",
              value: "●",
            },
            { key: "外饰氛围灯(门把手、侧面车型标识）", value: "●" },
            { key: "外后视镜迎宾照地灯", value: "●" },
            { key: "后排深色防紫外线隐私玻璃", value: "●" },
            { key: "17英寸NOCTIS铝合金轮毂", value: "●" },
            { key: "18英寸TOSCANA铝合金轮毂", value: "○2" },
            { key: "补胎套装", value: "●" },
            { key: "内饰", value: "" },
            { key: "三幅真皮方向盘", value: "-" },
            { key: "真皮多功能方向盘", value: "●" },
            { key: "真铝换挡手柄", value: "-" },
            { key: "Vienna打孔真皮座椅", value: "●" },
            { key: "前排座椅12向电动调节(含4向电动腰托调节)", value: "●" },
            { key: "副驾驶座椅后排电动可调", value: "●" },
            { key: "后排座椅4/6可分折叠", value: "●" },
            { key: "豪华内饰格调氛围灯", value: "-" },
            {
              key: "尊贵内饰格调氛围灯（含30色可变的仪表台及车门装饰条氛围灯等）",
              value: "●",
            },
            { key: "后排出风口", value: "●" },
            { key: '"GTE"标识LED迎宾踏板饰条', value: "●" },
            { key: 'LED光"GTE"徽标金属迎宾踏板', value: "-" },
            { key: "高亮钢琴漆中控台装饰面板", value: "●" },
          ],
        },
        {
          name: "安全/科技",
          list: [
            { key: "激光焊接技术", value: "●" },
            { key: "热成型钢板HSB高强度安全车身", value: "●" },
            { key: "智能在线防盗系统", value: "●" },
            { key: "前排正面双安全气囊", value: "●" },
            { key: "前排侧面双安全气囊", value: "●" },
            { key: "前后贯穿式两侧头部安全气帘", value: "●" },
            { key: "后排侧面双安全气囊", value: "●" },
            { key: "驾驶员膝部安全气囊", value: "●" },
            { key: "前/后8探头泊车雷达", value: "-" },
            {
              key: "PLA 3.0智能自动泊车辅助系统（全方位12探头泊车雷达）",
              value: "●",
            },
            {
              key: "RVC泊车后视影像系统（大众徽标翻盖隐藏式摄像头）",
              value: "-",
            },
            { key: "Area View 360°鸟瞰式全景可视泊车辅助系统", value: "●" },
            { key: "EPB智能电子手刹+Autohold自动驻车", value: "●" },
            {
              key: "全功能ESP车身稳定系统（含ABS, ASR, HBA等多项扩展功能）",
              value: "●",
            },
            { key: "MKB多次碰撞预防系统", value: "●" },
            { key: "RKA智能胎压监测系统", value: "-" },
            { key: "TPMS主动式智能胎压监测系统", value: "●" },
            { key: "MKE智能疲劳监测系统", value: "●" },
            { key: "GRA定速巡航系统", value: "-" },
            { key: "ACC 3.0高级自适应巡航系统", value: "●" },
            {
              key: "Front Assist预碰撞安全系统（含CEB城市紧急制动）",
              value: "●",
            },
            { key: "Pre-Crash 基础与前预碰撞保护系统", value: "●" },
            { key: "儿童座椅固定装置（ISOFIX+Top Tether）", value: "●" },
            { key: "前后排安全带未系提醒", value: "●" },
            { key: "前排电机式预紧限力安全带", value: "●" },
            { key: "自动防眩目内后视镜", value: "●" },
          ],
        },
        {
          name: "功能/豪华",
          list: [
            { key: "发动机启停及能量回收系统", value: "●" },
            { key: "充电预约管理", value: "●" },
            { key: "GTE专属运动模式", value: "●" },
            { key: "大灯感光自动开启", value: "●" },
            { key: "前大灯离回家功能", value: "●" },
            { key: "智能雨量感应无骨雨刷", value: "●" },
            { key: "智能一键启动系统", value: "●" },
            { key: "KESSY智能四门无钥匙进入系统", value: "●" },
            { key: "后备厢脚部感应开启", value: "●" },
            {
              key: "后备厢电动启合功能（带Easy Close舒适关闭功能）",
              value: "●",
            },
            { key: "智能触控式三区自动恒温空调系统", value: "●" },
            { key: "AQS空气质量自动控制系统", value: "●" },
            { key: "CLEAN AIR PM 2.5空气净化系统", value: "●" },
            { key: "外后视镜加热、电动调节功能（集成LED转向灯）", value: "●" },
            { key: "外后视镜电动折叠与锁车自动折叠", value: "●" },
            { key: "副司机侧外后视镜倒车辅助", value: "●" },
            { key: "驾驶员座椅记忆功能带舒适进入", value: "●" },
            { key: "四门一键式防夹电动车窗", value: "●" },
            { key: "后风挡电加热功能", value: "●" },
            { key: "前排座椅加热功能", value: "●" },
            { key: "前排四向调节头枕", value: "●" },
            { key: "后排舒适睡眠头枕", value: "●" },
            { key: "后排USB充电接口", value: "●" },
            { key: "无线充电", value: "●" },
            { key: "顶棚USB充电接口（行车记录仪用）", value: "●" },
            { key: "智能中文显示行车电脑（彩屏）", value: "●" },
            { key: "高分辨率真彩智能中文显示行车电脑", value: "-" },
            { key: "高保真车载音响系统带8扬声器", value: "●" },
            { key: "车载蓝牙系统", value: "●" },
            { key: "全触控屏智能车载导航多媒体系统", value: "●" },
          ],
        },
      ],
    },
  ],
  mark: "",
};
