const car = {
  carName: "ID.4 CROZZ",
  carInfo: [
    {
      model: "标准续航PURE版 ",
      price: "",
      paramList: [
        {
          name: "参数",
          list: [
            { key: "长×宽×高(mm)", value: "4,592×1,852×1,629" },
            { key: "轴距(毫米)", value: "2,765" },
            { key: "NEDC综合工况续航里程（km）", value: "405 " },
            { key: "动力电池类型", value: "三元锂电池" },
            { key: "动力电池包容量(kWh)", value: "55.7" },
            { key: "动力电池温控方式", value: "智能液态冷却&低温加热管理系统" },
            { key: "DC直流标准快充最大功率(kW)", value: "100" },
            { key: "AC交流标准充电最大功率(kW)", value: "7.2" },
            { key: "驱动形式", value: "后置后驱" },
            { key: "驱动电机", value: "永磁同步电机" },
            { key: "驱动电机峰值功率(kW)", value: "125" },
            { key: "驱动电机峰值扭矩(Nm)", value: "310" },
            { key: "变速箱型式", value: "单级减速器" },
            { key: "最高车速(km/h)", value: "160" },
            {
              key: "悬架系统（前/后）",
              value: "前：麦弗逊式独立悬架 / 后：五连杆式独立悬架",
            },
            { key: "转向系统", value: "EPS电子助力转向" },
          ],
        },
        {
          name: "智能座舱",
          list: [
            { key: "驾驶员高清显示屏", value: "●" },
            { key: "12英寸触控屏导航系统", value: "●" },
            { key: "AR HUD增强现实平视显示系统", value: "-" },
            { key: "ID.light智能交互灯语系统", value: "●" },
            {
              key: "座舱智能触控(含灯光控制区、中央控制区、顶棚控制区)",
              value: "●",
            },
            { key: "30色可调内饰格调氛围灯", value: "-" },
            { key: "氛围灯色彩个性化分层调节", value: "-" },
            { key: "仪表板INS 3D触感透光饰条", value: "-" },
            { key: "双区智能空调", value: "●" },
            { key: "三区智能空调", value: "-" },
            { key: "Clean Air 3.0空气净化系统", value: "●" },
            { key: "负离子空气净化功能", value: "-" },
            {
              key: "harman/kardon®哈曼卡顿高级音响系统(含Bass低音炮)",
              value: "-",
            },
          ],
        },
        {
          name: "IQ.Light智能灯光系统",
          list: [
            { key: "LED灵眸前大灯(含透镜)", value: "●" },
            { key: "IQ.Light高级LED灵动矩阵式前大灯", value: "-" },
            { key: "MDFS智能动态灯光辅助功能", value: "-" },
            { key: "AFS大灯随动转向功能", value: "-" },
            { key: "前大灯感光自动开启功能", value: "●" },
            { key: "前大灯离回家功能", value: "●" },
            { key: "LED日间行车灯", value: "●" },
            { key: "前部贯穿式LED灯带", value: "-" },
            { key: "后部贯穿式LED尾灯", value: "●" },
            { key: "尾灯流水式动态转向功能", value: "-" },
            { key: "ID.Welcome前后动态迎宾模式", value: "-" },
            { key: "前后发光VW徽标", value: "-" },
            { key: "IQ. Drive", value: "" },
            { key: "Travel Assist一键式全速域驾驶辅助", value: "-" },
            { key: "Top View360°全景可视影像", value: "-" },
            { key: "ACC 3.0高级自适应巡航系统(带跟停功能)", value: "●" },
            {
              key: "Front Assist前部防碰撞自动刹车系统（含CEB城市紧急制动）",
              value: "●",
            },
            { key: "Lane Assist 车道保持系统", value: "●" },
            { key: "VZE交通标志识别", value: "●" },
            { key: "Side Assist变道辅助", value: "-" },
            { key: "RTA后侧横向来车预警功能", value: "-" },
            { key: "Pre-crash预碰撞乘员保护系统", value: "-" },
          ],
        },
        {
          name: "外部配置",
          list: [
            { key: "全景天幕(超大玻璃车顶)", value: "●" },
            { key: "Panorama全景天窗（可开启）", value: "-" },
            { key: "电动天幕/天窗遮阳帘", value: "●" },
            { key: "动感黑色车顶", value: "-" },
            { key: "车顶行李架", value: "●" },
            { key: "隐藏式门把手(带氛围灯)", value: "●" },
            { key: "银色装饰门把手", value: "-" },
            { key: "高亮黑外后视镜", value: "-" },
            { key: "主动进气格栅", value: "●" },
            { key: "高亮黑大包围(带侧边镀铬饰条)", value: "-" },
            { key: "后排隐私玻璃", value: "●" },
            { key: '"1st"专属侧徽标', value: "-" },
            { key: "电动调节外后视镜带LED转向灯、加热功能", value: "●" },
            { key: "外后视镜（LED）迎宾照地灯", value: "-" },
            { key: "外后视镜锁车自动折叠功能", value: "-" },
            { key: "副司机侧外后视镜倒车辅助", value: "-" },
            { key: "19英寸空气动力学铝轮辋+前后轮胎235/55 R19", value: "●" },
            {
              key: "19英寸空气动力学铝轮辋+前轮胎235/55 R19+后轮胎255/50 R19",
              value: "-",
            },
            {
              key: "20英寸动感铝轮辋+前轮胎235/50 R20+后轮胎255/45 R20",
              value: "-",
            },
            {
              key: "20英寸动感琉光金铝轮辋+前轮胎235/50 R20+后轮胎255/45 R20",
              value: "-",
            },
            {
              key: "21英寸高性能铝轮辋+前轮胎235/45 R21+后轮胎255/40 R21",
              value: "-",
            },
            { key: "自修复轮胎", value: "●" },
          ],
        },
        {
          name: "内部配置",
          list: [
            { key: "简约家居风格内饰", value: "●" },
            { key: "都市能量黑风格内饰", value: "-" },
            { key: "时尚典雅灰风格内饰", value: "-" },
            { key: "潮流强劲风格内饰", value: "-" },
            { key: "触控式多功能方向盘", value: "●" },
            { key: "真皮方向盘 ", value: "-" },
            { key: '方向盘专属"1st"标识', value: "-" },
            { key: "方向盘加热功能", value: "-" },
            { key: "顶棚遮阳板带化妆镜", value: "●" },
            { key: "生态皮质&高级织物镶拼座椅", value: "●" },
            { key: "高级生态皮质座椅", value: "-" },
            { key: "Vienna真皮&Dinamica绒面镶拼打孔座椅", value: "-" },
            { key: "前排8向电动调节座椅", value: "●" },
            { key: "前排12向电动调节座椅(含4向腰托)", value: "-" },
            { key: "前排座椅记忆功能", value: "-" },
            { key: "前排座椅Easy Entry舒适进入迎宾功能", value: "-" },
            { key: "前排座椅加热", value: "-" },
            { key: "前排座椅按摩功能", value: "-" },
            { key: "Play-Pause加速/刹车踏板", value: "●" },
            { key: "后排座椅可翻折", value: "●" },
            { key: "后排中央扶手", value: "-" },
            { key: "后排出风口", value: "●" },
            { key: "触控式前后排阅读灯", value: "●" },
            { key: "前排USB多媒体输入接口", value: "●" },
            { key: "后排双USB充电插口", value: "●" },
            { key: "高保真车载音响系统带7扬声器", value: "●" },
          ],
        },
        {
          name: "安全配置 ",
          list: [
            { key: "前排正面双安全气囊", value: "●" },
            { key: "前排侧面双安全气囊", value: "●" },
            { key: "前后贯穿式两侧头部安全气帘", value: "●" },
            { key: "前排三点预紧式安全带,带限力功能", value: "●" },
            { key: "前排可逆式电机主动预紧安全带", value: "-" },
            { key: "前排安全带未系提醒", value: "●" },
            { key: "后排安全带未系提醒", value: "-" },
            { key: "Auto Hold 自动驻车", value: "●" },
            { key: "EPB 电子驻车", value: "●" },
            {
              key: "ESP车身稳定系统（含ABS, ASR, HBA等多项扩展功能）",
              value: "●",
            },
            { key: "自动防眩内后视镜", value: "-" },
            { key: "MKE疲劳监测系统", value: "●" },
            { key: "MKB多次碰撞预防系统", value: "●" },
            { key: "ISOFIX儿童座椅固定装置", value: "●" },
            { key: "RKA智能胎压监测系统", value: "●" },
            { key: "RVC泊车后视影像系统", value: "●" },
            { key: "前后泊车雷达", value: "●" },
            { key: "泊车紧急制动功能", value: "●" },
          ],
        },
        {
          name: "舒适/驾控功能 ",
          list: [
            { key: "KESSY高级无钥匙进入系统", value: "●" },
            { key: "KESSY智能一键启动系统", value: "●" },
            { key: "车载手机无线充电", value: "-" },
            { key: "无线&有线手机映射功能", value: "●" },
            { key: "FPA 驾驶模式选择", value: "●" },
            { key: "DCC智能动态底盘控制系统", value: "-" },
            { key: "电动尾门", value: "O6" },
            { key: "Easy open后备箱脚部感应开启", value: "O6" },
            { key: "Easy close后备箱脚部感应关闭", value: "O6" },
            { key: "前风挡清洗喷嘴加热", value: "-" },
            { key: "前风挡加热", value: "-" },
            { key: "CO2热泵空调系统", value: "-" },
            { key: "四门一键式防夹电动车窗", value: "●" },
            { key: "智能雨量感应无骨雨刷", value: "●" },
          ],
        },
        {
          name: "MOSC 4.0智慧车联系统",
          list: [
            { key: "智能语音交互", value: "●" },
            { key: "智慧在线导航", value: "●" },
            { key: "车载WiFi", value: "●" },
            { key: "手机App远程操控(空调开启及预约等)", value: "●" },
            { key: "E-Call紧急救援", value: "●" },
            { key: "智享娱乐(在线音乐、在线电台等)", value: "●" },
            { key: "智趣出行", value: "●" },
          ],
        },
      ],
    },
    {
      model: "长续航PURE+版",
      price: "",
      paramList: [
        {
          name: "参数",
          list: [
            { key: "长×宽×高(mm)", value: "4,592×1,852×1,629" },
            { key: "轴距(毫米)", value: "2,765" },
            { key: "NEDC综合工况续航里程（km）", value: "550  " },
            { key: "动力电池类型", value: "三元锂电池" },
            { key: "动力电池包容量(kWh)", value: "84.8" },
            { key: "动力电池温控方式", value: "智能液态冷却&低温加热管理系统" },
            { key: "DC直流标准快充最大功率(kW)", value: "100" },
            { key: "AC交流标准充电最大功率(kW)", value: "7.2" },
            { key: "驱动形式", value: "后置后驱" },
            { key: "驱动电机", value: "永磁同步电机" },
            { key: "驱动电机峰值功率(kW)", value: "150" },
            { key: "驱动电机峰值扭矩(Nm)", value: "310" },
            { key: "变速箱型式", value: "单级减速器" },
            { key: "最高车速(km/h)", value: "160" },
            {
              key: "悬架系统（前/后）",
              value: "前：麦弗逊式独立悬架 / 后：五连杆式独立悬架",
            },
            { key: "转向系统", value: "EPS电子助力转向" },
          ],
        },
        {
          name: "智能座舱",
          list: [
            { key: "驾驶员高清显示屏", value: "●" },
            { key: "12英寸触控屏导航系统", value: "●" },
            { key: "AR HUD增强现实平视显示系统", value: "-" },
            { key: "ID.light智能交互灯语系统", value: "●" },
            {
              key: "座舱智能触控(含灯光控制区、中央控制区、顶棚控制区)",
              value: "●",
            },
            { key: "30色可调内饰格调氛围灯", value: "-" },
            { key: "氛围灯色彩个性化分层调节", value: "-" },
            { key: "仪表板INS 3D触感透光饰条", value: "-" },
            { key: "双区智能空调", value: "●" },
            { key: "三区智能空调", value: "-" },
            { key: "Clean Air 3.0空气净化系统", value: "●" },
            { key: "负离子空气净化功能", value: "-" },
            {
              key: "harman/kardon®哈曼卡顿高级音响系统(含Bass低音炮)",
              value: "-",
            },
          ],
        },
        {
          name: "IQ.Light智能灯光系统",
          list: [
            { key: "LED灵眸前大灯(含透镜)", value: "●" },
            { key: "IQ.Light高级LED灵动矩阵式前大灯", value: "-" },
            { key: "MDFS智能动态灯光辅助功能", value: "-" },
            { key: "AFS大灯随动转向功能", value: "-" },
            { key: "前大灯感光自动开启功能", value: "●" },
            { key: "前大灯离回家功能", value: "●" },
            { key: "LED日间行车灯", value: "●" },
            { key: "前部贯穿式LED灯带", value: "-" },
            { key: "后部贯穿式LED尾灯", value: "●" },
            { key: "尾灯流水式动态转向功能", value: "-" },
            { key: "ID.Welcome前后动态迎宾模式", value: "-" },
            { key: "前后发光VW徽标", value: "-" },
            { key: "IQ. Drive", value: "" },
            { key: "Travel Assist一键式全速域驾驶辅助", value: "-" },
            { key: "Top View360°全景可视影像", value: "-" },
            { key: "ACC 3.0高级自适应巡航系统(带跟停功能)", value: "●" },
            {
              key: "Front Assist前部防碰撞自动刹车系统（含CEB城市紧急制动）",
              value: "●",
            },
            { key: "Lane Assist 车道保持系统", value: "●" },
            { key: "VZE交通标志识别", value: "●" },
            { key: "Side Assist变道辅助", value: "-" },
            { key: "RTA后侧横向来车预警功能", value: "-" },
            { key: "Pre-crash预碰撞乘员保护系统", value: "-" },
          ],
        },
        {
          name: "外部配置",
          list: [
            { key: "全景天幕(超大玻璃车顶)", value: "●" },
            { key: "Panorama全景天窗（可开启）", value: "O4" },
            { key: "电动天幕/天窗遮阳帘", value: "●" },
            { key: "动感黑色车顶", value: "-" },
            { key: "车顶行李架", value: "●" },
            { key: "隐藏式门把手(带氛围灯)", value: "●" },
            { key: "银色装饰门把手", value: "-" },
            { key: "高亮黑外后视镜", value: "-" },
            { key: "主动进气格栅", value: "●" },
            { key: "高亮黑大包围(带侧边镀铬饰条)", value: "-" },
            { key: "后排隐私玻璃", value: "●" },
            { key: '"1st"专属侧徽标', value: "-" },
            { key: "电动调节外后视镜带LED转向灯、加热功能", value: "●" },
            { key: "外后视镜（LED）迎宾照地灯", value: "-" },
            { key: "外后视镜锁车自动折叠功能", value: "-" },
            { key: "副司机侧外后视镜倒车辅助", value: "-" },
            { key: "19英寸空气动力学铝轮辋+前后轮胎235/55 R19", value: "-" },
            {
              key: "19英寸空气动力学铝轮辋+前轮胎235/55 R19+后轮胎255/50 R19",
              value: "●",
            },
            {
              key: "20英寸动感铝轮辋+前轮胎235/50 R20+后轮胎255/45 R20",
              value: "O5",
            },
            {
              key: "20英寸动感琉光金铝轮辋+前轮胎235/50 R20+后轮胎255/45 R20",
              value: "-",
            },
            {
              key: "21英寸高性能铝轮辋+前轮胎235/45 R21+后轮胎255/40 R21",
              value: "-",
            },
            { key: "自修复轮胎", value: "●" },
          ],
        },
        {
          name: "内部配置",
          list: [
            { key: "简约家居风格内饰", value: "●" },
            { key: "都市能量黑风格内饰", value: "-" },
            { key: "时尚典雅灰风格内饰", value: "-" },
            { key: "潮流强劲风格内饰", value: "-" },
            { key: "触控式多功能方向盘", value: "●" },
            { key: "真皮方向盘 ", value: "-" },
            { key: '方向盘专属"1st"标识', value: "-" },
            { key: "方向盘加热功能", value: "-" },
            { key: "顶棚遮阳板带化妆镜", value: "●" },
            { key: "生态皮质&高级织物镶拼座椅", value: "●" },
            { key: "高级生态皮质座椅", value: "-" },
            { key: "Vienna真皮&Dinamica绒面镶拼打孔座椅", value: "-" },
            { key: "前排8向电动调节座椅", value: "●" },
            { key: "前排12向电动调节座椅(含4向腰托)", value: "-" },
            { key: "前排座椅记忆功能", value: "-" },
            { key: "前排座椅Easy Entry舒适进入迎宾功能", value: "-" },
            { key: "前排座椅加热", value: "-" },
            { key: "前排座椅按摩功能", value: "-" },
            { key: "Play-Pause加速/刹车踏板", value: "●" },
            { key: "后排座椅可翻折", value: "●" },
            { key: "后排中央扶手", value: "-" },
            { key: "后排出风口", value: "●" },
            { key: "触控式前后排阅读灯", value: "●" },
            { key: "前排USB多媒体输入接口", value: "●" },
            { key: "后排双USB充电插口", value: "●" },
            { key: "高保真车载音响系统带7扬声器", value: "●" },
          ],
        },
        {
          name: "安全配置 ",
          list: [
            { key: "前排正面双安全气囊", value: "●" },
            { key: "前排侧面双安全气囊", value: "●" },
            { key: "前后贯穿式两侧头部安全气帘", value: "●" },
            { key: "前排三点预紧式安全带,带限力功能", value: "●" },
            { key: "前排可逆式电机主动预紧安全带", value: "-" },
            { key: "前排安全带未系提醒", value: "●" },
            { key: "后排安全带未系提醒", value: "-" },
            { key: "Auto Hold 自动驻车", value: "●" },
            { key: "EPB 电子驻车", value: "●" },
            {
              key: "ESP车身稳定系统（含ABS, ASR, HBA等多项扩展功能）",
              value: "●",
            },
            { key: "自动防眩内后视镜", value: "-" },
            { key: "MKE疲劳监测系统", value: "●" },
            { key: "MKB多次碰撞预防系统", value: "●" },
            { key: "ISOFIX儿童座椅固定装置", value: "●" },
            { key: "RKA智能胎压监测系统", value: "●" },
            { key: "RVC泊车后视影像系统", value: "●" },
            { key: "前后泊车雷达", value: "●" },
            { key: "泊车紧急制动功能", value: "●" },
          ],
        },
        {
          name: "舒适/驾控功能 ",
          list: [
            { key: "KESSY高级无钥匙进入系统", value: "●" },
            { key: "KESSY智能一键启动系统", value: "●" },
            { key: "车载手机无线充电", value: "-" },
            { key: "无线&有线手机映射功能", value: "●" },
            { key: "FPA 驾驶模式选择", value: "●" },
            { key: "DCC智能动态底盘控制系统", value: "-" },
            { key: "电动尾门", value: "●" },
            { key: "Easy open后备箱脚部感应开启", value: "●" },
            { key: "Easy close后备箱脚部感应关闭", value: "●" },
            { key: "前风挡清洗喷嘴加热", value: "O7" },
            { key: "前风挡加热", value: "O7" },
            { key: "CO2热泵空调系统", value: "O7" },
            { key: "四门一键式防夹电动车窗", value: "●" },
            { key: "智能雨量感应无骨雨刷", value: "●" },
          ],
        },
        {
          name: "MOSC 4.0智慧车联系统",
          list: [
            { key: "智能语音交互", value: "●" },
            { key: "智慧在线导航", value: "●" },
            { key: "车载WiFi", value: "●" },
            { key: "手机App远程操控(空调开启及预约等)", value: "●" },
            { key: "E-Call紧急救援", value: "●" },
            { key: "智享娱乐(在线音乐、在线电台等)", value: "●" },
            { key: "智趣出行", value: "●" },
          ],
        },
      ],
    },
    {
      model: "长续航PRO版",
      price: "",
      paramList: [
        {
          name: "参数",
          list: [
            { key: "长×宽×高(mm)", value: "4,592×1,852×1,629" },
            { key: "轴距(毫米)", value: "2,765" },
            { key: "NEDC综合工况续航里程（km）", value: "550  " },
            { key: "动力电池类型", value: "三元锂电池" },
            { key: "动力电池包容量(kWh)", value: "84.8" },
            { key: "动力电池温控方式", value: "智能液态冷却&低温加热管理系统" },
            { key: "DC直流标准快充最大功率(kW)", value: "100" },
            { key: "AC交流标准充电最大功率(kW)", value: "7.2" },
            { key: "驱动形式", value: "后置后驱" },
            { key: "驱动电机", value: "永磁同步电机" },
            { key: "驱动电机峰值功率(kW)", value: "150" },
            { key: "驱动电机峰值扭矩(Nm)", value: "310" },
            { key: "变速箱型式", value: "单级减速器" },
            { key: "最高车速(km/h)", value: "160" },
            {
              key: "悬架系统（前/后）",
              value: "前：麦弗逊式独立悬架 / 后：五连杆式独立悬架",
            },
            { key: "转向系统", value: "EPS电子助力转向" },
          ],
        },
        {
          name: "智能座舱",
          list: [
            { key: "驾驶员高清显示屏", value: "●" },
            { key: "12英寸触控屏导航系统", value: "●" },
            { key: "AR HUD增强现实平视显示系统", value: "O1" },
            { key: "ID.light智能交互灯语系统", value: "●" },
            {
              key: "座舱智能触控(含灯光控制区、中央控制区、顶棚控制区)",
              value: "●",
            },
            { key: "30色可调内饰格调氛围灯", value: "●" },
            { key: "氛围灯色彩个性化分层调节", value: "●" },
            { key: "仪表板INS 3D触感透光饰条", value: "O2" },
            { key: "双区智能空调", value: "●" },
            { key: "三区智能空调", value: "-" },
            { key: "Clean Air 3.0空气净化系统", value: "●" },
            { key: "负离子空气净化功能", value: "-" },
            {
              key: "harman/kardon®哈曼卡顿高级音响系统(含Bass低音炮)",
              value: "O3",
            },
          ],
        },
        {
          name: "IQ.Light智能灯光系统",
          list: [
            { key: "LED灵眸前大灯(含透镜)", value: "-" },
            { key: "IQ.Light高级LED灵动矩阵式前大灯", value: "●" },
            { key: "MDFS智能动态灯光辅助功能", value: "●" },
            { key: "AFS大灯随动转向功能", value: "●" },
            { key: "前大灯感光自动开启功能", value: "●" },
            { key: "前大灯离回家功能", value: "●" },
            { key: "LED日间行车灯", value: "●" },
            { key: "前部贯穿式LED灯带", value: "●" },
            { key: "后部贯穿式LED尾灯", value: "●" },
            { key: "尾灯流水式动态转向功能", value: "●" },
            { key: "ID.Welcome前后动态迎宾模式", value: "●" },
            { key: "前后发光VW徽标", value: "●" },
            { key: "IQ. Drive", value: "" },
            { key: "Travel Assist一键式全速域驾驶辅助", value: "●" },
            { key: "Top View360°全景可视影像", value: "●" },
            { key: "ACC 3.0高级自适应巡航系统(带跟停功能)", value: "●" },
            {
              key: "Front Assist前部防碰撞自动刹车系统（含CEB城市紧急制动）",
              value: "●",
            },
            { key: "Lane Assist 车道保持系统", value: "●" },
            { key: "VZE交通标志识别", value: "●" },
            { key: "Side Assist变道辅助", value: "●" },
            { key: "RTA后侧横向来车预警功能", value: "●" },
            { key: "Pre-crash预碰撞乘员保护系统", value: "-" },
          ],
        },
        {
          name: "外部配置",
          list: [
            { key: "全景天幕(超大玻璃车顶)", value: "●" },
            { key: "Panorama全景天窗（可开启）", value: "O4" },
            { key: "电动天幕/天窗遮阳帘", value: "●" },
            { key: "动感黑色车顶", value: "●" },
            { key: "车顶行李架", value: "●" },
            { key: "隐藏式门把手(带氛围灯)", value: "●" },
            { key: "银色装饰门把手", value: "●" },
            { key: "高亮黑外后视镜", value: "●" },
            { key: "主动进气格栅", value: "●" },
            { key: "高亮黑大包围(带侧边镀铬饰条)", value: "O2" },
            { key: "后排隐私玻璃", value: "●" },
            { key: '"1st"专属侧徽标', value: "-" },
            { key: "电动调节外后视镜带LED转向灯、加热功能", value: "●" },
            { key: "外后视镜（LED）迎宾照地灯", value: "●" },
            { key: "外后视镜锁车自动折叠功能", value: "●" },
            { key: "副司机侧外后视镜倒车辅助", value: "●" },
            { key: "19英寸空气动力学铝轮辋+前后轮胎235/55 R19", value: "-" },
            {
              key: "19英寸空气动力学铝轮辋+前轮胎235/55 R19+后轮胎255/50 R19",
              value: "-",
            },
            {
              key: "20英寸动感铝轮辋+前轮胎235/50 R20+后轮胎255/45 R20",
              value: "●",
            },
            {
              key: "20英寸动感琉光金铝轮辋+前轮胎235/50 R20+后轮胎255/45 R20",
              value: "-",
            },
            {
              key: "21英寸高性能铝轮辋+前轮胎235/45 R21+后轮胎255/40 R21",
              value: "-",
            },
            { key: "自修复轮胎", value: "●" },
          ],
        },
        {
          name: "内部配置",
          list: [
            { key: "简约家居风格内饰", value: "-" },
            { key: "都市能量黑风格内饰", value: "●" },
            { key: "时尚典雅灰风格内饰", value: "O" },
            { key: "潮流强劲风格内饰", value: "-" },
            { key: "触控式多功能方向盘", value: "●" },
            { key: "真皮方向盘 ", value: "●" },
            { key: '方向盘专属"1st"标识', value: "-" },
            { key: "方向盘加热功能", value: "●" },
            { key: "顶棚遮阳板带化妆镜", value: "●" },
            { key: "生态皮质&高级织物镶拼座椅", value: "-" },
            { key: "高级生态皮质座椅", value: "●" },
            { key: "Vienna真皮&Dinamica绒面镶拼打孔座椅", value: "-" },
            { key: "前排8向电动调节座椅", value: "-" },
            { key: "前排12向电动调节座椅(含4向腰托)", value: "●" },
            { key: "前排座椅记忆功能", value: "●" },
            { key: "前排座椅Easy Entry舒适进入迎宾功能", value: "●" },
            { key: "前排座椅加热", value: "●" },
            { key: "前排座椅按摩功能", value: "●" },
            { key: "Play-Pause加速/刹车踏板", value: "●" },
            { key: "后排座椅可翻折", value: "●" },
            { key: "后排中央扶手", value: "●" },
            { key: "后排出风口", value: "●" },
            { key: "触控式前后排阅读灯", value: "●" },
            { key: "前排USB多媒体输入接口", value: "●" },
            { key: "后排双USB充电插口", value: "●" },
            { key: "高保真车载音响系统带7扬声器", value: "●" },
          ],
        },
        {
          name: "安全配置 ",
          list: [
            { key: "前排正面双安全气囊", value: "●" },
            { key: "前排侧面双安全气囊", value: "●" },
            { key: "前后贯穿式两侧头部安全气帘", value: "●" },
            { key: "前排三点预紧式安全带,带限力功能", value: "●" },
            { key: "前排可逆式电机主动预紧安全带", value: "-" },
            { key: "前排安全带未系提醒", value: "●" },
            { key: "后排安全带未系提醒", value: "●" },
            { key: "Auto Hold 自动驻车", value: "●" },
            { key: "EPB 电子驻车", value: "●" },
            {
              key: "ESP车身稳定系统（含ABS, ASR, HBA等多项扩展功能）",
              value: "●",
            },
            { key: "自动防眩内后视镜", value: "●" },
            { key: "MKE疲劳监测系统", value: "●" },
            { key: "MKB多次碰撞预防系统", value: "●" },
            { key: "ISOFIX儿童座椅固定装置", value: "●" },
            { key: "RKA智能胎压监测系统", value: "●" },
            { key: "RVC泊车后视影像系统", value: "●" },
            { key: "前后泊车雷达", value: "●" },
            { key: "泊车紧急制动功能", value: "●" },
          ],
        },
        {
          name: "舒适/驾控功能 ",
          list: [
            { key: "KESSY高级无钥匙进入系统", value: "●" },
            { key: "KESSY智能一键启动系统", value: "●" },
            { key: "车载手机无线充电", value: "●" },
            { key: "无线&有线手机映射功能", value: "●" },
            { key: "FPA 驾驶模式选择", value: "●" },
            { key: "DCC智能动态底盘控制系统", value: "-" },
            { key: "电动尾门", value: "●" },
            { key: "Easy open后备箱脚部感应开启", value: "●" },
            { key: "Easy close后备箱脚部感应关闭", value: "●" },
            { key: "前风挡清洗喷嘴加热", value: "O7" },
            { key: "前风挡加热", value: "O7" },
            { key: "CO2热泵空调系统", value: "O7" },
            { key: "四门一键式防夹电动车窗", value: "●" },
            { key: "智能雨量感应无骨雨刷", value: "●" },
          ],
        },
        {
          name: "MOSC 4.0智慧车联系统",
          list: [
            { key: "智能语音交互", value: "●" },
            { key: "智慧在线导航", value: "●" },
            { key: "车载WiFi", value: "●" },
            { key: "手机App远程操控(空调开启及预约等)", value: "●" },
            { key: "E-Call紧急救援", value: "●" },
            { key: "智享娱乐(在线音乐、在线电台等)", value: "●" },
            { key: "智趣出行", value: "●" },
          ],
        },
      ],
    },
    {
      model: "曜夜首发版",
      price: "",
      paramList: [
        {
          name: "参数",
          list: [
            { key: "长×宽×高(mm)", value: "4,592×1,852×1,629" },
            { key: "轴距(毫米)", value: "2,765" },
            { key: "NEDC综合工况续航里程（km）", value: "550  " },
            { key: "动力电池类型", value: "三元锂电池" },
            { key: "动力电池包容量(kWh)", value: "84.8" },
            { key: "动力电池温控方式", value: "智能液态冷却&低温加热管理系统" },
            { key: "DC直流标准快充最大功率(kW)", value: "100" },
            { key: "AC交流标准充电最大功率(kW)", value: "7.2" },
            { key: "驱动形式", value: "后置后驱" },
            { key: "驱动电机", value: "永磁同步电机" },
            { key: "驱动电机峰值功率(kW)", value: "150" },
            { key: "驱动电机峰值扭矩(Nm)", value: "310" },
            { key: "变速箱型式", value: "单级减速器" },
            { key: "最高车速(km/h)", value: "160" },
            {
              key: "悬架系统（前/后）",
              value: "前：麦弗逊式独立悬架 / 后：五连杆式独立悬架",
            },
            { key: "转向系统", value: "EPS电子助力转向" },
          ],
        },
        {
          name: "智能座舱",
          list: [
            { key: "驾驶员高清显示屏", value: "●" },
            { key: "12英寸触控屏导航系统", value: "●" },
            { key: "AR HUD增强现实平视显示系统", value: "●" },
            { key: "ID.light智能交互灯语系统", value: "●" },
            {
              key: "座舱智能触控(含灯光控制区、中央控制区、顶棚控制区)",
              value: "●",
            },
            { key: "30色可调内饰格调氛围灯", value: "●" },
            { key: "氛围灯色彩个性化分层调节", value: "●" },
            { key: "仪表板INS 3D触感透光饰条", value: "-" },
            { key: "双区智能空调", value: "●" },
            { key: "三区智能空调", value: "-" },
            { key: "Clean Air 3.0空气净化系统", value: "●" },
            { key: "负离子空气净化功能", value: "-" },
            {
              key: "harman/kardon®哈曼卡顿高级音响系统(含Bass低音炮)",
              value: "-",
            },
          ],
        },
        {
          name: "IQ.Light智能灯光系统",
          list: [
            { key: "LED灵眸前大灯(含透镜)", value: "-" },
            { key: "IQ.Light高级LED灵动矩阵式前大灯", value: "●" },
            { key: "MDFS智能动态灯光辅助功能", value: "●" },
            { key: "AFS大灯随动转向功能", value: "●" },
            { key: "前大灯感光自动开启功能", value: "●" },
            { key: "前大灯离回家功能", value: "●" },
            { key: "LED日间行车灯", value: "●" },
            { key: "前部贯穿式LED灯带", value: "●" },
            { key: "后部贯穿式LED尾灯", value: "●" },
            { key: "尾灯流水式动态转向功能", value: "●" },
            { key: "ID.Welcome前后动态迎宾模式", value: "●" },
            { key: "前后发光VW徽标", value: "●" },
            { key: "IQ. Drive", value: "" },
            { key: "Travel Assist一键式全速域驾驶辅助", value: "●" },
            { key: "Top View360°全景可视影像", value: "●" },
            { key: "ACC 3.0高级自适应巡航系统(带跟停功能)", value: "●" },
            {
              key: "Front Assist前部防碰撞自动刹车系统（含CEB城市紧急制动）",
              value: "●",
            },
            { key: "Lane Assist 车道保持系统", value: "●" },
            { key: "VZE交通标志识别", value: "●" },
            { key: "Side Assist变道辅助", value: "●" },
            { key: "RTA后侧横向来车预警功能", value: "●" },
            { key: "Pre-crash预碰撞乘员保护系统", value: "-" },
          ],
        },
        {
          name: "外部配置",
          list: [
            { key: "全景天幕(超大玻璃车顶)", value: "●" },
            { key: "Panorama全景天窗（可开启）", value: "-" },
            { key: "电动天幕/天窗遮阳帘", value: "●" },
            { key: "动感黑色车顶", value: "●" },
            { key: "车顶行李架", value: "●" },
            { key: "隐藏式门把手(带氛围灯)", value: "●" },
            { key: "银色装饰门把手", value: "●" },
            { key: "高亮黑外后视镜", value: "●" },
            { key: "主动进气格栅", value: "●" },
            { key: "高亮黑大包围(带侧边镀铬饰条)", value: "-" },
            { key: "后排隐私玻璃", value: "●" },
            { key: '"1st"专属侧徽标', value: "●" },
            { key: "电动调节外后视镜带LED转向灯、加热功能", value: "●" },
            { key: "外后视镜（LED）迎宾照地灯", value: "●" },
            { key: "外后视镜锁车自动折叠功能", value: "●" },
            { key: "副司机侧外后视镜倒车辅助", value: "●" },
            { key: "19英寸空气动力学铝轮辋+前后轮胎235/55 R19", value: "-" },
            {
              key: "19英寸空气动力学铝轮辋+前轮胎235/55 R19+后轮胎255/50 R19",
              value: "-",
            },
            {
              key: "20英寸动感铝轮辋+前轮胎235/50 R20+后轮胎255/45 R20",
              value: "-",
            },
            {
              key: "20英寸动感琉光金铝轮辋+前轮胎235/50 R20+后轮胎255/45 R20",
              value: "●",
            },
            {
              key: "21英寸高性能铝轮辋+前轮胎235/45 R21+后轮胎255/40 R21",
              value: "-",
            },
            { key: "自修复轮胎", value: "●" },
          ],
        },
        {
          name: "内部配置",
          list: [
            { key: "简约家居风格内饰", value: "-" },
            { key: "都市能量黑风格内饰", value: "●" },
            { key: "时尚典雅灰风格内饰", value: "-" },
            { key: "潮流强劲风格内饰", value: "-" },
            { key: "触控式多功能方向盘", value: "●" },
            { key: "真皮方向盘 ", value: "●" },
            { key: '方向盘专属"1st"标识', value: "●" },
            { key: "方向盘加热功能", value: "●" },
            { key: "顶棚遮阳板带化妆镜", value: "●" },
            { key: "生态皮质&高级织物镶拼座椅", value: "-" },
            { key: "高级生态皮质座椅", value: "●" },
            { key: "Vienna真皮&Dinamica绒面镶拼打孔座椅", value: "-" },
            { key: "前排8向电动调节座椅", value: "-" },
            { key: "前排12向电动调节座椅(含4向腰托)", value: "●" },
            { key: "前排座椅记忆功能", value: "●" },
            { key: "前排座椅Easy Entry舒适进入迎宾功能", value: "●" },
            { key: "前排座椅加热", value: "●" },
            { key: "前排座椅按摩功能", value: "●" },
            { key: "Play-Pause加速/刹车踏板", value: "●" },
            { key: "后排座椅可翻折", value: "●" },
            { key: "后排中央扶手", value: "●" },
            { key: "后排出风口", value: "●" },
            { key: "触控式前后排阅读灯", value: "●" },
            { key: "前排USB多媒体输入接口", value: "●" },
            { key: "后排双USB充电插口", value: "●" },
            { key: "高保真车载音响系统带7扬声器", value: "●" },
          ],
        },
        {
          name: "安全配置 ",
          list: [
            { key: "前排正面双安全气囊", value: "●" },
            { key: "前排侧面双安全气囊", value: "●" },
            { key: "前后贯穿式两侧头部安全气帘", value: "●" },
            { key: "前排三点预紧式安全带,带限力功能", value: "●" },
            { key: "前排可逆式电机主动预紧安全带", value: "-" },
            { key: "前排安全带未系提醒", value: "●" },
            { key: "后排安全带未系提醒", value: "●" },
            { key: "Auto Hold 自动驻车", value: "●" },
            { key: "EPB 电子驻车", value: "●" },
            {
              key: "ESP车身稳定系统（含ABS, ASR, HBA等多项扩展功能）",
              value: "●",
            },
            { key: "自动防眩内后视镜", value: "●" },
            { key: "MKE疲劳监测系统", value: "●" },
            { key: "MKB多次碰撞预防系统", value: "●" },
            { key: "ISOFIX儿童座椅固定装置", value: "●" },
            { key: "RKA智能胎压监测系统", value: "●" },
            { key: "RVC泊车后视影像系统", value: "●" },
            { key: "前后泊车雷达", value: "●" },
            { key: "泊车紧急制动功能", value: "●" },
          ],
        },
        {
          name: "舒适/驾控功能 ",
          list: [
            { key: "KESSY高级无钥匙进入系统", value: "●" },
            { key: "KESSY智能一键启动系统", value: "●" },
            { key: "车载手机无线充电", value: "●" },
            { key: "无线&有线手机映射功能", value: "●" },
            { key: "FPA 驾驶模式选择", value: "●" },
            { key: "DCC智能动态底盘控制系统", value: "-" },
            { key: "电动尾门", value: "●" },
            { key: "Easy open后备箱脚部感应开启", value: "●" },
            { key: "Easy close后备箱脚部感应关闭", value: "●" },
            { key: "前风挡清洗喷嘴加热", value: "-" },
            { key: "前风挡加热", value: "-" },
            { key: "CO2热泵空调系统", value: "-" },
            { key: "四门一键式防夹电动车窗", value: "●" },
            { key: "智能雨量感应无骨雨刷", value: "●" },
          ],
        },
        {
          name: "MOSC 4.0智慧车联系统",
          list: [
            { key: "智能语音交互", value: "●" },
            { key: "智慧在线导航", value: "●" },
            { key: "车载WiFi", value: "●" },
            { key: "手机App远程操控(空调开启及预约等)", value: "●" },
            { key: "E-Call紧急救援", value: "●" },
            { key: "智享娱乐(在线音乐、在线电台等)", value: "●" },
            { key: "智趣出行", value: "●" },
          ],
        },
      ],
    },
    {
      model: "高性能PRIME抢鲜版",
      price: "",
      paramList: [
        {
          name: "参数",
          list: [
            { key: "长×宽×高(mm)", value: "4,592×1,852×1,629" },
            { key: "轴距(毫米)", value: "2,765" },
            { key: "NEDC综合工况续航里程（km）", value: "513 " },
            { key: "动力电池类型", value: "三元锂电池" },
            { key: "动力电池包容量(kWh)", value: "84.8" },
            { key: "动力电池温控方式", value: "智能液态冷却&低温加热管理系统" },
            { key: "DC直流标准快充最大功率(kW)", value: "100" },
            { key: "AC交流标准充电最大功率(kW)", value: "7.2" },
            { key: "驱动形式", value: "双电机四驱" },
            { key: "驱动电机", value: '"前：交流异步电机 后：永磁同步电机"' },
            { key: "驱动电机峰值功率(kW)", value: "80/150" },
            { key: "驱动电机峰值扭矩(Nm)", value: "460" },
            { key: "变速箱型式", value: "单级减速器" },
            { key: "最高车速(km/h)", value: "160" },
            {
              key: "悬架系统（前/后）",
              value: "前：麦弗逊式独立悬架 / 后：五连杆式独立悬架",
            },
            { key: "转向系统", value: "EPS电子助力转向" },
          ],
        },
        {
          name: "智能座舱",
          list: [
            { key: "驾驶员高清显示屏", value: "●" },
            { key: "12英寸触控屏导航系统", value: "●" },
            { key: "AR HUD增强现实平视显示系统", value: "●" },
            { key: "ID.light智能交互灯语系统", value: "●" },
            {
              key: "座舱智能触控(含灯光控制区、中央控制区、顶棚控制区)",
              value: "●",
            },
            { key: "30色可调内饰格调氛围灯", value: "●" },
            { key: "氛围灯色彩个性化分层调节", value: "●" },
            { key: "仪表板INS 3D触感透光饰条", value: "●" },
            { key: "双区智能空调", value: "-" },
            { key: "三区智能空调", value: "●" },
            { key: "Clean Air 3.0空气净化系统", value: "●" },
            { key: "负离子空气净化功能", value: "●" },
            {
              key: "harman/kardon®哈曼卡顿高级音响系统(含Bass低音炮)",
              value: "-",
            },
          ],
        },
        {
          name: "IQ.Light智能灯光系统",
          list: [
            { key: "LED灵眸前大灯(含透镜)", value: "-" },
            { key: "IQ.Light高级LED灵动矩阵式前大灯", value: "●" },
            { key: "MDFS智能动态灯光辅助功能", value: "●" },
            { key: "AFS大灯随动转向功能", value: "●" },
            { key: "前大灯感光自动开启功能", value: "●" },
            { key: "前大灯离回家功能", value: "●" },
            { key: "LED日间行车灯", value: "●" },
            { key: "前部贯穿式LED灯带", value: "●" },
            { key: "后部贯穿式LED尾灯", value: "●" },
            { key: "尾灯流水式动态转向功能", value: "●" },
            { key: "ID.Welcome前后动态迎宾模式", value: "●" },
            { key: "前后发光VW徽标", value: "●" },
            { key: "IQ. Drive", value: "" },
            { key: "Travel Assist一键式全速域驾驶辅助", value: "●" },
            { key: "Top View360°全景可视影像", value: "●" },
            { key: "ACC 3.0高级自适应巡航系统(带跟停功能)", value: "●" },
            {
              key: "Front Assist前部防碰撞自动刹车系统（含CEB城市紧急制动）",
              value: "●",
            },
            { key: "Lane Assist 车道保持系统", value: "●" },
            { key: "VZE交通标志识别", value: "●" },
            { key: "Side Assist变道辅助", value: "●" },
            { key: "RTA后侧横向来车预警功能", value: "●" },
            { key: "Pre-crash预碰撞乘员保护系统", value: "●" },
          ],
        },
        {
          name: "外部配置",
          list: [
            { key: "全景天幕(超大玻璃车顶)", value: "●" },
            { key: "Panorama全景天窗（可开启）", value: "O4" },
            { key: "电动天幕/天窗遮阳帘", value: "●" },
            { key: "动感黑色车顶", value: "●" },
            { key: "车顶行李架", value: "●" },
            { key: "隐藏式门把手(带氛围灯)", value: "●" },
            { key: "银色装饰门把手", value: "●" },
            { key: "高亮黑外后视镜", value: "●" },
            { key: "主动进气格栅", value: "●" },
            { key: "高亮黑大包围(带侧边镀铬饰条)", value: "●" },
            { key: "后排隐私玻璃", value: "●" },
            { key: '"1st"专属侧徽标', value: "-" },
            { key: "电动调节外后视镜带LED转向灯、加热功能", value: "●" },
            { key: "外后视镜（LED）迎宾照地灯", value: "●" },
            { key: "外后视镜锁车自动折叠功能", value: "●" },
            { key: "副司机侧外后视镜倒车辅助", value: "●" },
            { key: "19英寸空气动力学铝轮辋+前后轮胎235/55 R19", value: "-" },
            {
              key: "19英寸空气动力学铝轮辋+前轮胎235/55 R19+后轮胎255/50 R19",
              value: "-",
            },
            {
              key: "20英寸动感铝轮辋+前轮胎235/50 R20+后轮胎255/45 R20",
              value: "-",
            },
            {
              key: "20英寸动感琉光金铝轮辋+前轮胎235/50 R20+后轮胎255/45 R20",
              value: "-",
            },
            {
              key: "21英寸高性能铝轮辋+前轮胎235/45 R21+后轮胎255/40 R21",
              value: "●",
            },
            { key: "自修复轮胎", value: "●" },
          ],
        },
        {
          name: "内部配置",
          list: [
            { key: "简约家居风格内饰", value: "-" },
            { key: "都市能量黑风格内饰", value: "-" },
            { key: "时尚典雅灰风格内饰", value: "-" },
            { key: "潮流强劲风格内饰", value: "●" },
            { key: "触控式多功能方向盘", value: "●" },
            { key: "真皮方向盘 ", value: "●" },
            { key: '方向盘专属"1st"标识', value: "-" },
            { key: "方向盘加热功能", value: "●" },
            { key: "顶棚遮阳板带化妆镜", value: "●" },
            { key: "生态皮质&高级织物镶拼座椅", value: "-" },
            { key: "高级生态皮质座椅", value: "-" },
            { key: "Vienna真皮&Dinamica绒面镶拼打孔座椅", value: "●" },
            { key: "前排8向电动调节座椅", value: "-" },
            { key: "前排12向电动调节座椅(含4向腰托)", value: "●" },
            { key: "前排座椅记忆功能", value: "●" },
            { key: "前排座椅Easy Entry舒适进入迎宾功能", value: "●" },
            { key: "前排座椅加热", value: "●" },
            { key: "前排座椅按摩功能", value: "●" },
            { key: "Play-Pause加速/刹车踏板", value: "●" },
            { key: "后排座椅可翻折", value: "●" },
            { key: "后排中央扶手", value: "●" },
            { key: "后排出风口", value: "●" },
            { key: "触控式前后排阅读灯", value: "●" },
            { key: "前排USB多媒体输入接口", value: "●" },
            { key: "后排双USB充电插口", value: "●" },
            { key: "高保真车载音响系统带7扬声器", value: "●" },
          ],
        },
        {
          name: "安全配置 ",
          list: [
            { key: "前排正面双安全气囊", value: "●" },
            { key: "前排侧面双安全气囊", value: "●" },
            { key: "前后贯穿式两侧头部安全气帘", value: "●" },
            { key: "前排三点预紧式安全带,带限力功能", value: "-" },
            { key: "前排可逆式电机主动预紧安全带", value: "●" },
            { key: "前排安全带未系提醒", value: "●" },
            { key: "后排安全带未系提醒", value: "●" },
            { key: "Auto Hold 自动驻车", value: "●" },
            { key: "EPB 电子驻车", value: "●" },
            {
              key: "ESP车身稳定系统（含ABS, ASR, HBA等多项扩展功能）",
              value: "●",
            },
            { key: "自动防眩内后视镜", value: "●" },
            { key: "MKE疲劳监测系统", value: "●" },
            { key: "MKB多次碰撞预防系统", value: "●" },
            { key: "ISOFIX儿童座椅固定装置", value: "●" },
            { key: "RKA智能胎压监测系统", value: "●" },
            { key: "RVC泊车后视影像系统", value: "●" },
            { key: "前后泊车雷达", value: "●" },
            { key: "泊车紧急制动功能", value: "●" },
          ],
        },
        {
          name: "舒适/驾控功能 ",
          list: [
            { key: "KESSY高级无钥匙进入系统", value: "●" },
            { key: "KESSY智能一键启动系统", value: "●" },
            { key: "车载手机无线充电", value: "●" },
            { key: "无线&有线手机映射功能", value: "●" },
            { key: "FPA 驾驶模式选择", value: "●" },
            { key: "DCC智能动态底盘控制系统", value: "●" },
            { key: "电动尾门", value: "●" },
            { key: "Easy open后备箱脚部感应开启", value: "●" },
            { key: "Easy close后备箱脚部感应关闭", value: "●" },
            { key: "前风挡清洗喷嘴加热", value: "O7" },
            { key: "前风挡加热", value: "O7" },
            { key: "CO2热泵空调系统", value: "O7" },
            { key: "四门一键式防夹电动车窗", value: "●" },
            { key: "智能雨量感应无骨雨刷", value: "●" },
          ],
        },
        {
          name: "MOSC 4.0智慧车联系统",
          list: [
            { key: "智能语音交互", value: "●" },
            { key: "智慧在线导航", value: "●" },
            { key: "车载WiFi", value: "●" },
            { key: "手机App远程操控(空调开启及预约等)", value: "●" },
            { key: "E-Call紧急救援", value: "●" },
            { key: "智享娱乐(在线音乐、在线电台等)", value: "●" },
            { key: "智趣出行", value: "●" },
          ],
        },
      ],
    },
    {
      model: "高性能PRIME版 ",
      price: "",
      paramList: [
        {
          name: "参数",
          list: [
            { key: "长×宽×高(mm)", value: "4,592×1,852×1,629" },
            { key: "轴距(毫米)", value: "2,765" },
            { key: "NEDC综合工况续航里程（km）", value: "513 " },
            { key: "动力电池类型", value: "三元锂电池" },
            { key: "动力电池包容量(kWh)", value: "84.8" },
            { key: "动力电池温控方式", value: "智能液态冷却&低温加热管理系统" },
            { key: "DC直流标准快充最大功率(kW)", value: "100" },
            { key: "AC交流标准充电最大功率(kW)", value: "7.2" },
            { key: "驱动形式", value: "双电机四驱" },
            { key: "驱动电机", value: '"前：交流异步电机 后：永磁同步电机"' },
            { key: "驱动电机峰值功率(kW)", value: "80/150" },
            { key: "驱动电机峰值扭矩(Nm)", value: "460" },
            { key: "变速箱型式", value: "单级减速器" },
            { key: "最高车速(km/h)", value: "160" },
            {
              key: "悬架系统（前/后）",
              value: "前：麦弗逊式独立悬架 / 后：五连杆式独立悬架",
            },
            { key: "转向系统", value: "EPS电子助力转向" },
          ],
        },
        {
          name: "智能座舱",
          list: [
            { key: "驾驶员高清显示屏", value: "●" },
            { key: "12英寸触控屏导航系统", value: "●" },
            { key: "AR HUD增强现实平视显示系统", value: "●" },
            { key: "ID.light智能交互灯语系统", value: "●" },
            {
              key: "座舱智能触控(含灯光控制区、中央控制区、顶棚控制区)",
              value: "●",
            },
            { key: "30色可调内饰格调氛围灯", value: "●" },
            { key: "氛围灯色彩个性化分层调节", value: "●" },
            { key: "仪表板INS 3D触感透光饰条", value: "●" },
            { key: "双区智能空调", value: "-" },
            { key: "三区智能空调", value: "●" },
            { key: "Clean Air 3.0空气净化系统", value: "●" },
            { key: "负离子空气净化功能", value: "●" },
            {
              key: "harman/kardon®哈曼卡顿高级音响系统(含Bass低音炮)",
              value: "●",
            },
          ],
        },
        {
          name: "IQ.Light智能灯光系统",
          list: [
            { key: "LED灵眸前大灯(含透镜)", value: "-" },
            { key: "IQ.Light高级LED灵动矩阵式前大灯", value: "●" },
            { key: "MDFS智能动态灯光辅助功能", value: "●" },
            { key: "AFS大灯随动转向功能", value: "●" },
            { key: "前大灯感光自动开启功能", value: "●" },
            { key: "前大灯离回家功能", value: "●" },
            { key: "LED日间行车灯", value: "●" },
            { key: "前部贯穿式LED灯带", value: "●" },
            { key: "后部贯穿式LED尾灯", value: "●" },
            { key: "尾灯流水式动态转向功能", value: "●" },
            { key: "ID.Welcome前后动态迎宾模式", value: "●" },
            { key: "前后发光VW徽标", value: "●" },
            { key: "IQ. Drive", value: "" },
            { key: "Travel Assist一键式全速域驾驶辅助", value: "●" },
            { key: "Top View360°全景可视影像", value: "●" },
            { key: "ACC 3.0高级自适应巡航系统(带跟停功能)", value: "●" },
            {
              key: "Front Assist前部防碰撞自动刹车系统（含CEB城市紧急制动）",
              value: "●",
            },
            { key: "Lane Assist 车道保持系统", value: "●" },
            { key: "VZE交通标志识别", value: "●" },
            { key: "Side Assist变道辅助", value: "●" },
            { key: "RTA后侧横向来车预警功能", value: "●" },
            { key: "Pre-crash预碰撞乘员保护系统", value: "●" },
          ],
        },
        {
          name: "外部配置",
          list: [
            { key: "全景天幕(超大玻璃车顶)", value: "●" },
            { key: "Panorama全景天窗（可开启）", value: "O4" },
            { key: "电动天幕/天窗遮阳帘", value: "●" },
            { key: "动感黑色车顶", value: "●" },
            { key: "车顶行李架", value: "●" },
            { key: "隐藏式门把手(带氛围灯)", value: "●" },
            { key: "银色装饰门把手", value: "●" },
            { key: "高亮黑外后视镜", value: "●" },
            { key: "主动进气格栅", value: "●" },
            { key: "高亮黑大包围(带侧边镀铬饰条)", value: "●" },
            { key: "后排隐私玻璃", value: "●" },
            { key: '"1st"专属侧徽标', value: "-" },
            { key: "电动调节外后视镜带LED转向灯、加热功能", value: "●" },
            { key: "外后视镜（LED）迎宾照地灯", value: "●" },
            { key: "外后视镜锁车自动折叠功能", value: "●" },
            { key: "副司机侧外后视镜倒车辅助", value: "●" },
            { key: "19英寸空气动力学铝轮辋+前后轮胎235/55 R19", value: "-" },
            {
              key: "19英寸空气动力学铝轮辋+前轮胎235/55 R19+后轮胎255/50 R19",
              value: "-",
            },
            {
              key: "20英寸动感铝轮辋+前轮胎235/50 R20+后轮胎255/45 R20",
              value: "-",
            },
            {
              key: "20英寸动感琉光金铝轮辋+前轮胎235/50 R20+后轮胎255/45 R20",
              value: "-",
            },
            {
              key: "21英寸高性能铝轮辋+前轮胎235/45 R21+后轮胎255/40 R21",
              value: "●",
            },
            { key: "自修复轮胎", value: "●" },
          ],
        },
        {
          name: "内部配置",
          list: [
            { key: "简约家居风格内饰", value: "-" },
            { key: "都市能量黑风格内饰", value: "-" },
            { key: "时尚典雅灰风格内饰", value: "-" },
            { key: "潮流强劲风格内饰", value: "●" },
            { key: "触控式多功能方向盘", value: "●" },
            { key: "真皮方向盘 ", value: "●" },
            { key: '方向盘专属"1st"标识', value: "-" },
            { key: "方向盘加热功能", value: "●" },
            { key: "顶棚遮阳板带化妆镜", value: "●" },
            { key: "生态皮质&高级织物镶拼座椅", value: "-" },
            { key: "高级生态皮质座椅", value: "-" },
            { key: "Vienna真皮&Dinamica绒面镶拼打孔座椅", value: "●" },
            { key: "前排8向电动调节座椅", value: "-" },
            { key: "前排12向电动调节座椅(含4向腰托)", value: "●" },
            { key: "前排座椅记忆功能", value: "●" },
            { key: "前排座椅Easy Entry舒适进入迎宾功能", value: "●" },
            { key: "前排座椅加热", value: "●" },
            { key: "前排座椅按摩功能", value: "●" },
            { key: "Play-Pause加速/刹车踏板", value: "●" },
            { key: "后排座椅可翻折", value: "●" },
            { key: "后排中央扶手", value: "●" },
            { key: "后排出风口", value: "●" },
            { key: "触控式前后排阅读灯", value: "●" },
            { key: "前排USB多媒体输入接口", value: "●" },
            { key: "后排双USB充电插口", value: "●" },
            { key: "高保真车载音响系统带7扬声器", value: "-" },
          ],
        },
        {
          name: "安全配置 ",
          list: [
            { key: "前排正面双安全气囊", value: "●" },
            { key: "前排侧面双安全气囊", value: "●" },
            { key: "前后贯穿式两侧头部安全气帘", value: "●" },
            { key: "前排三点预紧式安全带,带限力功能", value: "-" },
            { key: "前排可逆式电机主动预紧安全带", value: "●" },
            { key: "前排安全带未系提醒", value: "●" },
            { key: "后排安全带未系提醒", value: "●" },
            { key: "Auto Hold 自动驻车", value: "●" },
            { key: "EPB 电子驻车", value: "●" },
            {
              key: "ESP车身稳定系统（含ABS, ASR, HBA等多项扩展功能）",
              value: "●",
            },
            { key: "自动防眩内后视镜", value: "●" },
            { key: "MKE疲劳监测系统", value: "●" },
            { key: "MKB多次碰撞预防系统", value: "●" },
            { key: "ISOFIX儿童座椅固定装置", value: "●" },
            { key: "RKA智能胎压监测系统", value: "●" },
            { key: "RVC泊车后视影像系统", value: "●" },
            { key: "前后泊车雷达", value: "●" },
            { key: "泊车紧急制动功能", value: "●" },
          ],
        },
        {
          name: "舒适/驾控功能 ",
          list: [
            { key: "KESSY高级无钥匙进入系统", value: "●" },
            { key: "KESSY智能一键启动系统", value: "●" },
            { key: "车载手机无线充电", value: "●" },
            { key: "无线&有线手机映射功能", value: "●" },
            { key: "FPA 驾驶模式选择", value: "●" },
            { key: "DCC智能动态底盘控制系统", value: "●" },
            { key: "电动尾门", value: "●" },
            { key: "Easy open后备箱脚部感应开启", value: "●" },
            { key: "Easy close后备箱脚部感应关闭", value: "●" },
            { key: "前风挡清洗喷嘴加热", value: "O7" },
            { key: "前风挡加热", value: "O7" },
            { key: "CO2热泵空调系统", value: "O7" },
            { key: "四门一键式防夹电动车窗", value: "●" },
            { key: "智能雨量感应无骨雨刷", value: "●" },
          ],
        },
        {
          name: "MOSC 4.0智慧车联系统",
          list: [
            { key: "智能语音交互", value: "●" },
            { key: "智慧在线导航", value: "●" },
            { key: "车载WiFi", value: "●" },
            { key: "手机App远程操控(空调开启及预约等)", value: "●" },
            { key: "E-Call紧急救援", value: "●" },
            { key: "智享娱乐(在线音乐、在线电台等)", value: "●" },
            { key: "智趣出行", value: "●" },
          ],
        },
      ],
    },
  ],
  mark: [
    "1. ● 表示有此配置          ○ 可选配备       - 表示无此配置",
    {
      name: "2. 选装包定义：",
      list: [
        { key: "O1 AR HUD增强现实平视显示系统", item: [] },
        { key: "O2 尊崇风格套件", item: [] },
        {
          key: "O3 harman/kardon®哈曼卡顿高级音响系统(含Bass低音炮)",
          item: ["高亮黑大包围(带侧边镀铬饰条)", "仪表板INS 3D触感透光饰条"],
        },
        { key: "O4 Panorama可开启全景天窗", item: [] },
        {
          key: "O5 20英寸动感车轮包",
          item: ["20英寸动感铝轮辋", "前轮胎235/50 R20+后轮胎255/45 R20"],
        },
        {
          key: "O6 舒适尾门包",
          item: [
            "电动尾门",
            "Easy open后备箱脚部感应开启",
            "Easy close后备箱脚部感应关闭",
          ],
        },
        {
          key: "O7 CO2热泵空调包",
          item: ["CO2热泵空调系统", "前风挡清洗喷嘴加热", "前风挡加热"],
        },
      ],
    },
    "3. 外饰颜色：极地白、珠光白、星河灰、量子金、星黛蓝、以太红、曜夜蓝（首发版专属）。",
    "4. 本清单若出现以下情况（包括但不限于）：国家相关法律法规的强制要求、技术进步、产品更新和零部件供应商调整等，一汽-大众汽车有限公司保留对产品价格、外观颜色、技术参数、配置装备和车型代号等信息修改权利。电池续航里程及充电时间仅供参考，受实际使用情况影响而变化。",
    "5. 此配置信息仅作为产品配置参考，最终产品配置及功能以交付为准，一汽-大众汽车有限公司有权对产品配置在合法范围内进行细微调整。",
  ],
};
