const car = {
  carName: "探岳GTE",
  carInfo: [
    {
      model: "豪华型",
      price: "249800",
      paramList: [
        {
          name: "技术参数",
          list: [
            { key: "长×宽×高(mm)", value: " 4,603 x1,860 x 1,658 " },
            { key: "轴距(mm)", value: "2,730 " },
            { key: "后备厢容积(L)", value: "413" },
            { key: "油箱容积(L)", value: "47" },
            { key: "整备质量(kg)", value: "1,835" },
            { key: "发动机型式", value: "EA211直列四缸16气阀电控燃油喷射" },
            { key: "发动机排量(L)", value: "1.395 " },
            { key: "额定功率(kW/rpm)", value: "110/5500-6000" },
            { key: "最大扭矩(N·m/rpm)", value: "250/1750-3000" },
            { key: "电动机峰值功率(kW)", value: "85" },
            { key: "电动机峰值扭矩(N·m)", value: "330" },
            { key: "系统最大功率(kW/rpm)", value: "155" },
            { key: "系统最大扭矩(N·m)", value: "400" },
            { key: "变速箱型式", value: "DQ400e 6挡湿式DSG®双离合手自一体" },
            { key: "驱动方式", value: "前驱" },
            { key: "最高车速(km/h)", value: "200" },
            { key: "电池系统额定能量（Ah）", value: "37" },
            { key: "工信部纯电续航里程(km)", value: "54" },
            { key: "0-100km/h加速(s)", value: "8.4 " },
            { key: "工信部综合油耗(L/100km)", value: "2.0 " },
            {
              key: "悬架系统（前/后）",
              value: "前：麦弗逊式独立悬挂结构 / 后：多连杆式独立悬挂结构 ",
            },
            { key: "制动系统", value: "前：通风盘式 / 后：实心盘式" },
            { key: "转向系统", value: "EPS电子助力转向系统" },
            { key: "排放标准", value: "国六排放标准" },
          ],
        },
        {
          name: "外饰",
          list: [
            { key: "亮银色铝合金车顶行李架", value: "●" },
            { key: "双色车顶（黑色）", value: "—" },
            { key: "Panoroma大尺寸全景天窗", value: "●" },
            { key: "电动天窗遮阳帘", value: "●" },
            { key: "高级LED透镜前大灯", value: "●" },
            { key: "AFS大灯随动转向功能", value: "●" },
            { key: "前大灯离回家功能", value: "●" },
            { key: "前大灯感光自动开启功能", value: "●" },
            { key: "C形LED 日行灯", value: "●" },
            { key: "钢琴烤漆轮拱及侧裙边", value: "●" },
            {
              key: "多功能外后视镜（带LED转向灯，电动可调，加热）",
              value: "●",
            },
            { key: "外后视镜照地灯（带VW GTE标识）", value: "●" },
            { key: "外后视镜停车自动折叠", value: "●" },
            { key: "副司机侧外后视镜倒车辅助", value: "●" },
            { key: "外饰氛围灯（门把手、侧标牌）", value: "●" },
            { key: "全LED尾灯", value: "●" },
            { key: "“蜂窝链”式前格栅", value: "●" },
            { key: "前格栅专属GTE标识", value: "●" },
            { key: "翼子板专属GTE标识", value: "●" },
            { key: "鲨鱼鳍天线", value: "●" },
            { key: "星轨状铝合金车顶轮廓线", value: "●" },
            { key: "双侧单出镀铬尾管", value: "●" },
            { key: "18英寸铝轮辋", value: "●" },
          ],
        },
        {
          name: "内饰",
          list: [
            { key: "黑色风格内饰", value: "●" },
            { key: "深蓝风格内饰", value: "O" },
            { key: "真皮多功能方向盘", value: "●" },
            { key: "方向盘加热功能", value: "—" },
            { key: "方向盘换挡拨片", value: "—" },
            { key: "长度/高度可调节方向盘", value: "●" },
            { key: "奢享真皮座椅(Alcantara侧翼）", value: "●" },
            { key: "奢享打孔真皮座椅", value: "—" },
            { key: "前排座椅加热", value: "●" },
            { key: "12向电动座椅调节（含腰托）", value: "●" },
            { key: "后排座椅4/2/4可分折叠", value: "●" },
            { key: "后排座椅前后/角度可调", value: "●" },
            { key: "后排座椅行李箱箱一键放倒", value: "●" },
            { key: "后排座椅中扶手（带通过式载物功能）", value: "●" },
            { key: "LED迎宾踏板饰条", value: "●" },
            { key: "豪华内饰格调氛围灯", value: "●" },
            { key: "尊贵内饰格调氛围灯", value: "—" },
          ],
        },
        {
          name: "安全",
          list: [
            { key: "前排正面安全气囊*2", value: "●" },
            { key: "前排侧面安全气囊*2", value: "●" },
            { key: "前后贯穿式两侧头部安全气帘", value: "●" },
            { key: "驾驶员膝部气囊", value: "●" },
            { key: "前排安全带未系提醒", value: "●" },
            { key: "后排安全带未系提醒", value: "●" },
            {
              key: "全功能ESP车身稳定系统（含ABS, ASR, HBA等多项扩展功能）",
              value: "●",
            },
            { key: "前后排高度可调头枕", value: "●" },
            {
              key: "Front Assist预碰撞安全系统（含CEB城市紧急制动）",
              value: "●",
            },
            { key: "SWA换道辅助", value: "—" },
            { key: "Lane Assist 车道保持系统", value: "—" },
            { key: "GRA 定速巡航系统", value: "●" },
            { key: "ACC 3.0高级自适应巡航系统", value: "—" },
            { key: "RTA后方交通预警系统", value: "—" },
            { key: "自动防炫目内后视镜", value: "●" },
            { key: "EPB电子驻车", value: "●" },
            { key: "ISOFIX儿童座椅固定装置", value: "●" },
            { key: "TPMS Warning Signal胎压监测报警系统", value: "—" },
            { key: "TPMS Digital Display主动式智能胎压监测系统", value: "O1 " },
            { key: "前后 泊车雷达", value: "●" },
            { key: "PLA 3.0智能泊车系统 ", value: "—" },
            { key: "Auto Hold 自动驻车", value: "●" },
            { key: "EPB 电子驻车", value: "●" },
            { key: "HHC坡道辅助系统", value: "●" },
            { key: "RVC泊车后视影像系统", value: "●" },
          ],
        },
        {
          name: "功能",
          list: [
            { key: "电动尾门", value: "●" },
            { key: "后备箱脚步感应开启", value: "●" },
            { key: "遥控钥匙", value: "●" },
            { key: "Kessy智能无钥匙进入系统", value: "●" },
            { key: "Kessy智能一键启动系统", value: "●" },
            { key: "行李厢盖板上下可调", value: "●" },
            { key: "发动机启停及能量回收系统", value: "●" },
            { key: "驾驶模式选择", value: "●" },
            { key: "前风挡清洗喷嘴加热", value: "—" },
            { key: "智能触控式三区自动恒温空调系统", value: "●" },
            { key: "CLEAN AIR PM 2.5空气净化系统", value: "●" },
            { key: "后排空调出风口", value: "●" },
            { key: "Active Info Display 全液晶数字仪表", value: "●" },
            { key: "全触控屏智能车载导航多媒体系统", value: "●" },
            { key: "蓝牙手机免提系统", value: "●" },
            { key: "6扬声器环绕立体声音响系统", value: "●" },
            { key: "8扬声器环绕立体声音响系统", value: "—" },
          ],
        },
      ],
    },
    {
      model: "尊贵型",
      price: "259800",
      paramList: [
        {
          name: "技术参数",
          list: [
            { key: "长×宽×高(mm)", value: " 4,603 x1,860 x 1,658 " },
            { key: "轴距(mm)", value: "2,730 " },
            { key: "后备厢容积(L)", value: "413" },
            { key: "油箱容积(L)", value: "47" },
            { key: "整备质量(kg)", value: "1,835" },
            { key: "发动机型式", value: "EA211直列四缸16气阀电控燃油喷射" },
            { key: "发动机排量(L)", value: "1.395 " },
            { key: "额定功率(kW/rpm)", value: "110/5500-6000" },
            { key: "最大扭矩(N·m/rpm)", value: "250/1750-3000" },
            { key: "电动机峰值功率(kW)", value: "85" },
            { key: "电动机峰值扭矩(N·m)", value: "330" },
            { key: "系统最大功率(kW/rpm)", value: "155" },
            { key: "系统最大扭矩(N·m)", value: "400" },
            { key: "变速箱型式", value: "DQ400e 6挡湿式DSG®双离合手自一体" },
            { key: "驱动方式", value: "前驱" },
            { key: "最高车速(km/h)", value: "200" },
            { key: "电池系统额定能量（Ah）", value: "37" },
            { key: "工信部纯电续航里程(km)", value: "54" },
            { key: "0-100km/h加速(s)", value: "8.4 " },
            { key: "工信部综合油耗(L/100km)", value: "2.0 " },
            {
              key: "悬架系统（前/后）",
              value: "前：麦弗逊式独立悬挂结构 / 后：多连杆式独立悬挂结构 ",
            },
            { key: "制动系统", value: "前：通风盘式 / 后：实心盘式" },
            { key: "转向系统", value: "EPS电子助力转向系统" },
            { key: "排放标准", value: "国六排放标准" },
          ],
        },
        {
          name: "外饰",
          list: [
            { key: "亮银色铝合金车顶行李架", value: "●" },
            { key: "双色车顶（黑色）", value: "●" },
            { key: "Panoroma大尺寸全景天窗", value: "●" },
            { key: "电动天窗遮阳帘", value: "●" },
            { key: "高级LED透镜前大灯", value: "●" },
            { key: "AFS大灯随动转向功能", value: "●" },
            { key: "前大灯离回家功能", value: "●" },
            { key: "前大灯感光自动开启功能", value: "●" },
            { key: "C形LED 日行灯", value: "●" },
            { key: "钢琴烤漆轮拱及侧裙边", value: "●" },
            {
              key: "多功能外后视镜（带LED转向灯，电动可调，加热）",
              value: "●",
            },
            { key: "外后视镜照地灯（带VW GTE标识）", value: "●" },
            { key: "外后视镜停车自动折叠", value: "●" },
            { key: "副司机侧外后视镜倒车辅助", value: "●" },
            { key: "外饰氛围灯（门把手、侧标牌）", value: "●" },
            { key: "全LED尾灯", value: "●" },
            { key: "“蜂窝链”式前格栅", value: "●" },
            { key: "前格栅专属GTE标识", value: "●" },
            { key: "翼子板专属GTE标识", value: "●" },
            { key: "鲨鱼鳍天线", value: "●" },
            { key: "星轨状铝合金车顶轮廓线", value: "●" },
            { key: "双侧单出镀铬尾管", value: "●" },
            { key: "18英寸铝轮辋", value: "●" },
          ],
        },
        {
          name: "内饰",
          list: [
            { key: "黑色风格内饰", value: "●" },
            { key: "深蓝风格内饰", value: "O" },
            { key: "真皮多功能方向盘", value: "●" },
            { key: "方向盘加热功能", value: "●" },
            { key: "方向盘换挡拨片", value: "●" },
            { key: "长度/高度可调节方向盘", value: "●" },
            { key: "奢享真皮座椅(Alcantara侧翼）", value: "—" },
            { key: "奢享打孔真皮座椅", value: "●" },
            { key: "前排座椅加热", value: "●" },
            { key: "12向电动座椅调节（含腰托）", value: "●" },
            { key: "后排座椅4/2/4可分折叠", value: "●" },
            { key: "后排座椅前后/角度可调", value: "●" },
            { key: "后排座椅行李箱箱一键放倒", value: "●" },
            { key: "后排座椅中扶手（带通过式载物功能）", value: "●" },
            { key: "LED迎宾踏板饰条", value: "●" },
            { key: "豪华内饰格调氛围灯", value: "—" },
            { key: "尊贵内饰格调氛围灯", value: "●" },
          ],
        },
        {
          name: "安全",
          list: [
            { key: "前排正面安全气囊*2", value: "●" },
            { key: "前排侧面安全气囊*2", value: "●" },
            { key: "前后贯穿式两侧头部安全气帘", value: "●" },
            { key: "驾驶员膝部气囊", value: "●" },
            { key: "前排安全带未系提醒", value: "●" },
            { key: "后排安全带未系提醒", value: "●" },
            {
              key: "全功能ESP车身稳定系统（含ABS, ASR, HBA等多项扩展功能）",
              value: "●",
            },
            { key: "前后排高度可调头枕", value: "●" },
            {
              key: "Front Assist预碰撞安全系统（含CEB城市紧急制动）",
              value: "●",
            },
            { key: "SWA换道辅助", value: "●" },
            { key: "Lane Assist 车道保持系统", value: "●" },
            { key: "GRA 定速巡航系统", value: "●" },
            { key: "ACC 3.0高级自适应巡航系统", value: "●" },
            { key: "RTA后方交通预警系统", value: "●" },
            { key: "自动防炫目内后视镜", value: "●" },
            { key: "EPB电子驻车", value: "●" },
            { key: "ISOFIX儿童座椅固定装置", value: "●" },
            { key: "TPMS Warning Signal胎压监测报警系统", value: "●" },
            { key: "TPMS Digital Display主动式智能胎压监测系统", value: "—" },
            { key: "前后 泊车雷达", value: "—" },
            { key: "PLA 3.0智能泊车系统 ", value: "●" },
            { key: "Auto Hold 自动驻车", value: "●" },
            { key: "EPB 电子驻车", value: "●" },
            { key: "HHC坡道辅助系统", value: "●" },
            { key: "RVC泊车后视影像系统", value: "●" },
          ],
        },
        {
          name: "功能",
          list: [
            { key: "电动尾门", value: "●" },
            { key: "后备箱脚步感应开启", value: "●" },
            { key: "遥控钥匙", value: "●" },
            { key: "Kessy智能无钥匙进入系统", value: "●" },
            { key: "Kessy智能一键启动系统", value: "●" },
            { key: "行李厢盖板上下可调", value: "●" },
            { key: "发动机启停及能量回收系统", value: "●" },
            { key: "驾驶模式选择", value: "●" },
            { key: "前风挡清洗喷嘴加热", value: "●" },
            { key: "智能触控式三区自动恒温空调系统", value: "●" },
            { key: "CLEAN AIR PM 2.5空气净化系统", value: "●" },
            { key: "后排空调出风口", value: "●" },
            { key: "Active Info Display 全液晶数字仪表", value: "●" },
            { key: "全触控屏智能车载导航多媒体系统", value: "●" },
            { key: "蓝牙手机免提系统", value: "●" },
            { key: "6扬声器环绕立体声音响系统", value: "—" },
            { key: "8扬声器环绕立体声音响系统", value: "●" },
          ],
        },
      ],
    },
  ],
  mark: [
    "1. ● 标准装备   ○ 选装装备     — 不提供",
    {
      name: "2. 选装包定义：",
      list: [
        { key: "O1 TPMS Digital Display主动式智能胎压监测系统", item: [] },
      ],
    },
    "3. 外饰颜色：锰石黑、极地白、星耀金、星辰蓝",
    "4. 本清单若出现以下情况（包括但不限于）：国家相关法律法规的强制要求、技术进步、产品更新和零部件供应商调整等，一汽-大众汽车有限公司保留对产品价格、外观颜色、技术参数、配置装备和车型代号等信息的修改权利。具体车型信息请以实车为准，或咨询当地经销商。",
  ],
};
