const car = {
  carName: "揽境",
  carInfo: [
    {
      model: "精英新境版",
      price: "253900",
      paramList: [
        {
          name: "技术参数",
          list: [
            { key: "长×宽×高(mm)", value: "5,152 × 2,002 × 1,795" },
            { key: "轴距(mm)", value: "2,980" },
            { key: "后备厢容积(L)", value: "357 / 942 (7座880)" },
            { key: "油箱容积(L)", value: "74" },
            { key: "整备质量(kg)", value: "2050" },
            { key: "发动机型式", value: "直列四缸 / 涡轮增压" },
            { key: "发动机排量(L)", value: "1.984" },
            { key: "额定功率(kW/rpm)", value: "137 / 4,100-6,000" },
            { key: "最大扭矩(N·m/rpm)", value: "320 / 1,600-4,050" },
            { key: "变速箱型式", value: "7速DSG®湿式双离合自动变速器" },
            { key: "驱动形式", value: "前轮驱动" },
            { key: "最高车速(km/h)", value: "200" },
            { key: "0-100km/h加速(s)", value: "10.8" },
            { key: "综合工况油耗(L/100km)", value: "7.2" },
            {
              key: "悬架系统（前/后）",
              value: "前麦弗逊式独立悬架/后多连杆式独立悬架",
            },
            { key: "制动系统", value: "前/后通风盘式制动" },
            { key: "转向系统", value: "EPS电动随速助力转向" },
            { key: "排放标准", value: "国六排放标准" },
          ],
        },
        {
          name: "外饰",
          list: [
            { key: "LED日间行车灯", value: "●" },
            { key: "贯穿式LED尾灯", value: "●" },
            { key: "外饰氛围灯(格栅、门把手、侧标、行李架)", value: "-" },
            { key: "天使之翼迎宾光毯灯", value: "-" },
            { key: "前大灯感光自动开启", value: "●" },
            { key: "前大灯离回家功能", value: "●" },
            { key: "R-Line专属运动风格套件", value: "-" },
            { key: "Panorama大尺寸全景天窗", value: "-" },
            { key: "后排隐私玻璃", value: "●" },
            { key: "后排VSG降噪隐私玻璃", value: "-" },
            { key: "亮银色车顶行李架", value: "●" },
            { key: "鲨鱼鳍天线", value: "●" },
            {
              key: "多功能外后视镜（带LED转向灯、电动调节、加热功能）",
              value: "●",
            },
            {
              key: "多功能外后视镜（带LED转向灯、电动调节、加热功能、停车自动折叠）",
              value: "-",
            },
            {
              key: "多功能外后视镜（带LED转向灯、电动调节、加热功能、停车自动折叠、自动防眩目）",
              value: "-",
            },
            { key: "副司机侧外后视镜倒车辅助", value: "-" },
            { key: "20英寸Malana铝合金轮辋", value: "●" },
            { key: "21英寸Sapporo铝合金轮辋", value: "-" },
            { key: "21英寸铝合金R-Line造型轮辋", value: "-" },
            { key: "双色车身（黑色车顶）", value: "-" },
            { key: "珠光白外饰漆", value: "-" },
          ],
        },
        {
          name: "内饰 ",
          list: [
            {
              key: "智能触控内饰(灯光/视野控制区、中央控制区、顶棚控制区)",
              value: "●",
            },
            { key: "Shift by wire电子换档", value: "●" },
            { key: "皮革包覆软质内饰带真缝线（仪表板、门板）", value: "●" },
            { key: "前排中央扶手（高度及长度可调）", value: "●" },
            { key: "真皮多功能方向盘带换挡拨片", value: "●" },
            { key: "触控式方向盘", value: "-" },
            { key: "方向盘加热", value: "-" },
            { key: "6座（2-2-2布局）", value: "●" },
            { key: "7座（2-3-2布局）", value: "O1" },
            { key: "精致PVC+织物镶拼座椅", value: "●" },
            { key: "Vienna材质打孔真皮座椅", value: "-" },
            { key: "Vienna材质R-Line专属打孔真皮座椅", value: "-" },
            { key: "司机侧12向电动调节座椅(含4向腰托)", value: "●" },
            { key: "副司机侧12向电动调节座椅(含4向腰托)", value: "●" },
            { key: "司机侧座椅记忆功能", value: "-" },
            { key: "前排座椅加热", value: "-" },
            { key: "第二排座椅加热", value: "-" },
            { key: "前排座椅通风", value: "-" },
            { key: "第二排老板座椅高级通风按摩功能", value: "-" },
            { key: "第二排老板座椅带两侧独立扶手、带杯架", value: "●" },
            { key: "第二排座椅4/6可分体折叠", value: "O1" },
            { key: "第二排座椅中扶手（带弹出式杯架）", value: "O1" },
            { key: "第二排/第三排出风口", value: "●" },
            { key: "透光饰条", value: "-" },
            { key: "透光饰条R-Line风格", value: "-" },
            { key: "30色可调内饰氛围灯", value: "-" },
            { key: "顶棚USB充电插口（行车记录仪用）", value: "●" },
            { key: "前排USB插口x4", value: "●" },
            { key: "6座第二排USB充电插口x4 ", value: "●" },
            { key: "7座第二排USB充电插口x2 ", value: "O1" },
            { key: "第三排USB充电插口x2", value: "●" },
            { key: "R-Line金属运动脚踏板", value: "-" },
            { key: "金属迎宾踏板饰条", value: "●" },
            { key: "LED迎宾踏板饰条", value: "-" },
          ],
        },
        {
          name: "安全",
          list: [
            { key: "前排正面安全气囊x2", value: "●" },
            { key: "前排侧面安全气囊x2", value: "●" },
            { key: "前后贯穿式两侧头部安全气帘x2", value: "●" },
            { key: "司机侧膝部安全气囊x1", value: "●" },
            { key: "第二排侧面安全气囊x2", value: "-" },
            { key: "前排高度可调预紧式安全带", value: "●" },
            { key: "后座预紧式安全带", value: "-" },
            { key: "前排安全带未系提醒", value: "●" },
            { key: "第二排安全带未系提醒", value: "-" },
            { key: "Auto Hold 自动驻车", value: "●" },
            { key: "EPB 电子驻车", value: "●" },
            { key: "ESP车身稳定系统", value: "●" },
            { key: "HDC陡坡缓降系统", value: "-" },
            { key: "自动防眩内后视镜", value: "●" },
            { key: "智能雨量感应无骨雨刷", value: "●" },
            { key: "MKE疲劳监测系统", value: "●" },
            { key: "MKB多次碰撞预防系统", value: "●" },
            { key: "ISOFIX儿童座椅固定装置", value: "●" },
            { key: "RKA智能胎压监测系统", value: "●" },
            { key: "TPMS Digital Display主动式智能胎压监测系统", value: "-" },
            { key: "前/后泊车雷达", value: "●" },
            { key: "RVC泊车后视影像系统", value: "-" },
            { key: "Top View 360°全景可视影像", value: "-" },
            { key: "开门预警系统", value: "-" },
          ],
        },
        {
          name: "功能",
          list: [
            { key: "Kessy智能（四门）无钥匙进入系统", value: "-" },
            { key: "Kessy智能一键启动系统", value: "●" },
            { key: "电动尾门", value: "●" },
            { key: "后备箱脚步感应开启", value: "-" },
            { key: "手机无线充电", value: "-" },
            { key: "10.25英寸全液晶数字仪表", value: "●" },
            { key: "手机映射（支持CarPlay等）", value: "●" },
            { key: "蓝牙手机免提系统", value: "●" },
            { key: "智能触控式三区自动恒温空调系统", value: "●" },
            { key: "Clean Air 3.0空气净化系统", value: "●" },
            { key: "前风挡加热", value: "-" },
            { key: "前风挡清洗喷嘴加热", value: "-" },
            { key: "高级智能平视显示系统wHUD", value: "-" },
            { key: "驾驶模式选择", value: "-" },
            { key: "DCC动态底盘控制系统", value: "-" },
            { key: "8扬声器高保真车载音响系统", value: "●" },
            { key: "Harman Kardon高级环绕音响带12扬声器", value: "-" },
          ],
        },
        {
          name: "车联网",
          list: [
            {
              key: "车联网 - 智联控车、智慧导航、智能语音、智享娱乐",
              value: "●",
            },
            {
              key: "CNS3.0智能车载导航信息娱乐系统：12英寸触摸彩屏",
              value: "●",
            },
            { key: "IQ. Drive", value: "" },
            { key: "GRA 定速巡航系统", value: "●" },
            { key: "ACC 3.0高级自适应巡航系统", value: "-" },
            {
              key: "Front Assist预碰撞安全系统（含AEB城市紧急制动）",
              value: "-",
            },
            { key: "PLA 3.0智能泊车系统", value: "O2" },
            { key: "BSD 盲点监测系统", value: "-" },
            { key: "Lane Assist 车道保持系统", value: "-" },
            { key: "Travel Assist 一键式智能驾驶辅助系统", value: "-" },
            { key: "VZE交通标志识别", value: "-" },
            { key: "Pre-Crash预碰撞保护系统", value: "-" },
            { key: "RTA后方交通预警系统", value: "-" },
            { key: "IQ. Light", value: "" },
            { key: "全天候LED前大灯", value: "●" },
            { key: "大灯高度自动调节功能", value: "●" },
            { key: "高级全LED前大灯", value: "-" },
            { key: "MDFS智能动态灯光辅助功能", value: "-" },
            { key: "AFS大灯随动转向功能", value: "-" },
            { key: "动态LED后转向灯", value: "-" },
          ],
        },
      ],
    },
    {
      model: "豪华佳境版",
      price: "268900",
      paramList: [
        {
          name: "技术参数",
          list: [
            { key: "长×宽×高(mm)", value: "5,152 × 2,002 × 1,795" },
            { key: "轴距(mm)", value: "2,980" },
            { key: "后备厢容积(L)", value: "357 / 942 (7座880)" },
            { key: "油箱容积(L)", value: "74" },
            { key: "整备质量(kg)", value: "2050" },
            { key: "发动机型式", value: "直列四缸 / 涡轮增压" },
            { key: "发动机排量(L)", value: "1.984" },
            { key: "额定功率(kW/rpm)", value: "137 / 4,100-6,000" },
            { key: "最大扭矩(N·m/rpm)", value: "320 / 1,600-4,050" },
            { key: "变速箱型式", value: "7速DSG®湿式双离合自动变速器" },
            { key: "驱动形式", value: "前轮驱动" },
            { key: "最高车速(km/h)", value: "200" },
            { key: "0-100km/h加速(s)", value: "10.8" },
            { key: "综合工况油耗(L/100km)", value: "7.2" },
            {
              key: "悬架系统（前/后）",
              value: "前麦弗逊式独立悬架/后多连杆式独立悬架",
            },
            { key: "制动系统", value: "前/后通风盘式制动" },
            { key: "转向系统", value: "EPS电动随速助力转向" },
            { key: "排放标准", value: "国六排放标准" },
          ],
        },
        {
          name: "外饰",
          list: [
            { key: "LED日间行车灯", value: "●" },
            { key: "贯穿式LED尾灯", value: "●" },
            { key: "外饰氛围灯(格栅、门把手、侧标、行李架)", value: "●" },
            { key: "天使之翼迎宾光毯灯", value: "●" },
            { key: "前大灯感光自动开启", value: "●" },
            { key: "前大灯离回家功能", value: "●" },
            { key: "R-Line专属运动风格套件", value: "-" },
            { key: "Panorama大尺寸全景天窗", value: "●" },
            { key: "后排隐私玻璃", value: "●" },
            { key: "后排VSG降噪隐私玻璃", value: "-" },
            { key: "亮银色车顶行李架", value: "●" },
            { key: "鲨鱼鳍天线", value: "●" },
            {
              key: "多功能外后视镜（带LED转向灯、电动调节、加热功能）",
              value: "-",
            },
            {
              key: "多功能外后视镜（带LED转向灯、电动调节、加热功能、停车自动折叠）",
              value: "●",
            },
            {
              key: "多功能外后视镜（带LED转向灯、电动调节、加热功能、停车自动折叠、自动防眩目）",
              value: "-",
            },
            { key: "副司机侧外后视镜倒车辅助", value: "●" },
            { key: "20英寸Malana铝合金轮辋", value: "●" },
            { key: "21英寸Sapporo铝合金轮辋", value: "-" },
            { key: "21英寸铝合金R-Line造型轮辋", value: "-" },
            { key: "双色车身（黑色车顶）", value: "O8" },
            { key: "珠光白外饰漆", value: "O10" },
          ],
        },
        {
          name: "内饰 ",
          list: [
            {
              key: "智能触控内饰(灯光/视野控制区、中央控制区、顶棚控制区)",
              value: "●",
            },
            { key: "Shift by wire电子换档", value: "●" },
            { key: "皮革包覆软质内饰带真缝线（仪表板、门板）", value: "●" },
            { key: "前排中央扶手（高度及长度可调）", value: "●" },
            { key: "真皮多功能方向盘带换挡拨片", value: "●" },
            { key: "触控式方向盘", value: "-" },
            { key: "方向盘加热", value: "O4" },
            { key: "6座（2-2-2布局）", value: "●" },
            { key: "7座（2-3-2布局）", value: "O1" },
            { key: "精致PVC+织物镶拼座椅", value: "-" },
            { key: "Vienna材质打孔真皮座椅", value: "●" },
            { key: "Vienna材质R-Line专属打孔真皮座椅", value: "-" },
            { key: "司机侧12向电动调节座椅(含4向腰托)", value: "●" },
            { key: "副司机侧12向电动调节座椅(含4向腰托)", value: "●" },
            { key: "司机侧座椅记忆功能", value: "●" },
            { key: "前排座椅加热", value: "●" },
            { key: "第二排座椅加热", value: "●" },
            { key: "前排座椅通风", value: "O9" },
            { key: "第二排老板座椅高级通风按摩功能", value: "-" },
            { key: "第二排老板座椅带两侧独立扶手、带杯架", value: "●" },
            { key: "第二排座椅4/6可分体折叠", value: "O1" },
            { key: "第二排座椅中扶手（带弹出式杯架）", value: "O1" },
            { key: "第二排/第三排出风口", value: "●" },
            { key: "透光饰条", value: "●" },
            { key: "透光饰条R-Line风格", value: "-" },
            { key: "30色可调内饰氛围灯", value: "●" },
            { key: "顶棚USB充电插口（行车记录仪用）", value: "●" },
            { key: "前排USB插口x4", value: "●" },
            { key: "6座第二排USB充电插口x4 ", value: "●" },
            { key: "7座第二排USB充电插口x2 ", value: "O1" },
            { key: "第三排USB充电插口x2", value: "●" },
            { key: "R-Line金属运动脚踏板", value: "-" },
            { key: "金属迎宾踏板饰条", value: "●" },
            { key: "LED迎宾踏板饰条", value: "-" },
          ],
        },
        {
          name: "安全",
          list: [
            { key: "前排正面安全气囊x2", value: "●" },
            { key: "前排侧面安全气囊x2", value: "●" },
            { key: "前后贯穿式两侧头部安全气帘x2", value: "●" },
            { key: "司机侧膝部安全气囊x1", value: "●" },
            { key: "第二排侧面安全气囊x2", value: "●" },
            { key: "前排高度可调预紧式安全带", value: "●" },
            { key: "后座预紧式安全带", value: "●" },
            { key: "前排安全带未系提醒", value: "●" },
            { key: "第二排安全带未系提醒", value: "-" },
            { key: "Auto Hold 自动驻车", value: "●" },
            { key: "EPB 电子驻车", value: "●" },
            { key: "ESP车身稳定系统", value: "●" },
            { key: "HDC陡坡缓降系统", value: "-" },
            { key: "自动防眩内后视镜", value: "●" },
            { key: "智能雨量感应无骨雨刷", value: "●" },
            { key: "MKE疲劳监测系统", value: "●" },
            { key: "MKB多次碰撞预防系统", value: "●" },
            { key: "ISOFIX儿童座椅固定装置", value: "●" },
            { key: "RKA智能胎压监测系统", value: "-" },
            { key: "TPMS Digital Display主动式智能胎压监测系统", value: "●" },
            { key: "前/后泊车雷达", value: "●" },
            { key: "RVC泊车后视影像系统", value: "-" },
            { key: "Top View 360°全景可视影像", value: "●" },
            { key: "开门预警系统", value: "-" },
          ],
        },
        {
          name: "功能",
          list: [
            { key: "Kessy智能（四门）无钥匙进入系统", value: "●" },
            { key: "Kessy智能一键启动系统", value: "●" },
            { key: "电动尾门", value: "●" },
            { key: "后备箱脚步感应开启", value: "●" },
            { key: "手机无线充电", value: "-" },
            { key: "10.25英寸全液晶数字仪表", value: "●" },
            { key: "手机映射（支持CarPlay等）", value: "●" },
            { key: "蓝牙手机免提系统", value: "●" },
            { key: "智能触控式三区自动恒温空调系统", value: "●" },
            { key: "Clean Air 3.0空气净化系统", value: "●" },
            { key: "前风挡加热", value: "O4" },
            { key: "前风挡清洗喷嘴加热", value: "O4" },
            { key: "高级智能平视显示系统wHUD", value: "-" },
            { key: "驾驶模式选择", value: "-" },
            { key: "DCC动态底盘控制系统", value: "-" },
            { key: "8扬声器高保真车载音响系统", value: "●" },
            { key: "Harman Kardon高级环绕音响带12扬声器", value: "-" },
          ],
        },
        {
          name: "车联网",
          list: [
            {
              key: "车联网 - 智联控车、智慧导航、智能语音、智享娱乐",
              value: "●",
            },
            {
              key: "CNS3.0智能车载导航信息娱乐系统：12英寸触摸彩屏",
              value: "●",
            },
            { key: "IQ. Drive", value: "" },
            { key: "GRA 定速巡航系统", value: "●" },
            { key: "ACC 3.0高级自适应巡航系统", value: "-" },
            {
              key: "Front Assist预碰撞安全系统（含AEB城市紧急制动）",
              value: "-",
            },
            { key: "PLA 3.0智能泊车系统", value: "●" },
            { key: "BSD 盲点监测系统", value: "-" },
            { key: "Lane Assist 车道保持系统", value: "-" },
            { key: "Travel Assist 一键式智能驾驶辅助系统", value: "-" },
            { key: "VZE交通标志识别", value: "-" },
            { key: "Pre-Crash预碰撞保护系统", value: "-" },
            { key: "RTA后方交通预警系统", value: "-" },
            { key: "IQ. Light", value: "" },
            { key: "全天候LED前大灯", value: "●" },
            { key: "大灯高度自动调节功能", value: "●" },
            { key: "高级全LED前大灯", value: "O3" },
            { key: "MDFS智能动态灯光辅助功能", value: "O3" },
            { key: "AFS大灯随动转向功能", value: "O3" },
            { key: "动态LED后转向灯", value: "●" },
          ],
        },
      ],
    },
    {
      model: "四驱 豪华佳境版Pro",
      price: "268900",
      paramList: [
        {
          name: "技术参数",
          list: [
            { key: "长×宽×高(mm)", value: "5,152 × 2,002 × 1,795" },
            { key: "轴距(mm)", value: "2,980" },
            { key: "后备厢容积(L)", value: "357 / 942 (7座880)" },
            { key: "油箱容积(L)", value: "74" },
            { key: "整备质量(kg)", value: "2160" },
            { key: "发动机型式", value: "直列四缸 / 涡轮增压" },
            { key: "发动机排量(L)", value: "1.984" },
            { key: "额定功率(kW/rpm)", value: "162 / 4,500-6,700" },
            { key: "最大扭矩(N·m/rpm)", value: "350 / 1,500-4,300" },
            { key: "变速箱型式", value: "7速DSG®湿式双离合自动变速器" },
            { key: "驱动形式", value: "四轮驱动" },
            { key: "最高车速(km/h)", value: "200" },
            { key: "0-100km/h加速(s)", value: "9.2" },
            { key: "综合工况油耗(L/100km)", value: "8.6" },
            {
              key: "悬架系统（前/后）",
              value: "前麦弗逊式独立悬架/后多连杆式独立悬架",
            },
            { key: "制动系统", value: "前/后通风盘式制动" },
            { key: "转向系统", value: "EPS电动随速助力转向" },
            { key: "排放标准", value: "国六排放标准" },
          ],
        },
        {
          name: "外饰",
          list: [
            { key: "LED日间行车灯", value: "●" },
            { key: "贯穿式LED尾灯", value: "●" },
            { key: "外饰氛围灯(格栅、门把手、侧标、行李架)", value: "●" },
            { key: "天使之翼迎宾光毯灯", value: "●" },
            { key: "前大灯感光自动开启", value: "●" },
            { key: "前大灯离回家功能", value: "●" },
            { key: "R-Line专属运动风格套件", value: "-" },
            { key: "Panorama大尺寸全景天窗", value: "●" },
            { key: "后排隐私玻璃", value: "●" },
            { key: "后排VSG降噪隐私玻璃", value: "-" },
            { key: "亮银色车顶行李架", value: "●" },
            { key: "鲨鱼鳍天线", value: "●" },
            {
              key: "多功能外后视镜（带LED转向灯、电动调节、加热功能）",
              value: "-",
            },
            {
              key: "多功能外后视镜（带LED转向灯、电动调节、加热功能、停车自动折叠）",
              value: "●",
            },
            {
              key: "多功能外后视镜（带LED转向灯、电动调节、加热功能、停车自动折叠、自动防眩目）",
              value: "-",
            },
            { key: "副司机侧外后视镜倒车辅助", value: "●" },
            { key: "20英寸Malana铝合金轮辋", value: "●" },
            { key: "21英寸Sapporo铝合金轮辋", value: "-" },
            { key: "21英寸铝合金R-Line造型轮辋", value: "-" },
            { key: "双色车身（黑色车顶）", value: "O8" },
            { key: "珠光白外饰漆", value: "O10" },
          ],
        },
        {
          name: "内饰 ",
          list: [
            {
              key: "智能触控内饰(灯光/视野控制区、中央控制区、顶棚控制区)",
              value: "●",
            },
            { key: "Shift by wire电子换档", value: "●" },
            { key: "皮革包覆软质内饰带真缝线（仪表板、门板）", value: "●" },
            { key: "前排中央扶手（高度及长度可调）", value: "●" },
            { key: "真皮多功能方向盘带换挡拨片", value: "●" },
            { key: "触控式方向盘", value: "-" },
            { key: "方向盘加热", value: "●" },
            { key: "6座（2-2-2布局）", value: "●" },
            { key: "7座（2-3-2布局）", value: "O1" },
            { key: "精致PVC+织物镶拼座椅", value: "-" },
            { key: "Vienna材质打孔真皮座椅", value: "●" },
            { key: "Vienna材质R-Line专属打孔真皮座椅", value: "-" },
            { key: "司机侧12向电动调节座椅(含4向腰托)", value: "●" },
            { key: "副司机侧12向电动调节座椅(含4向腰托)", value: "●" },
            { key: "司机侧座椅记忆功能", value: "●" },
            { key: "前排座椅加热", value: "●" },
            { key: "第二排座椅加热", value: "●" },
            { key: "前排座椅通风", value: "O9" },
            { key: "第二排老板座椅高级通风按摩功能", value: "-" },
            { key: "第二排老板座椅带两侧独立扶手、带杯架", value: "●" },
            { key: "第二排座椅4/6可分体折叠", value: "O1" },
            { key: "第二排座椅中扶手（带弹出式杯架）", value: "O1" },
            { key: "第二排/第三排出风口", value: "●" },
            { key: "透光饰条", value: "●" },
            { key: "透光饰条R-Line风格", value: "-" },
            { key: "30色可调内饰氛围灯", value: "●" },
            { key: "顶棚USB充电插口（行车记录仪用）", value: "●" },
            { key: "前排USB插口x4", value: "●" },
            { key: "6座第二排USB充电插口x4 ", value: "●" },
            { key: "7座第二排USB充电插口x2 ", value: "O1" },
            { key: "第三排USB充电插口x2", value: "●" },
            { key: "R-Line金属运动脚踏板", value: "-" },
            { key: "金属迎宾踏板饰条", value: "●" },
            { key: "LED迎宾踏板饰条", value: "-" },
          ],
        },
        {
          name: "安全",
          list: [
            { key: "前排正面安全气囊x2", value: "●" },
            { key: "前排侧面安全气囊x2", value: "●" },
            { key: "前后贯穿式两侧头部安全气帘x2", value: "●" },
            { key: "司机侧膝部安全气囊x1", value: "●" },
            { key: "第二排侧面安全气囊x2", value: "●" },
            { key: "前排高度可调预紧式安全带", value: "●" },
            { key: "后座预紧式安全带", value: "●" },
            { key: "前排安全带未系提醒", value: "●" },
            { key: "第二排安全带未系提醒", value: "●" },
            { key: "Auto Hold 自动驻车", value: "●" },
            { key: "EPB 电子驻车", value: "●" },
            { key: "ESP车身稳定系统", value: "●" },
            { key: "HDC陡坡缓降系统", value: "●" },
            { key: "自动防眩内后视镜", value: "●" },
            { key: "智能雨量感应无骨雨刷", value: "●" },
            { key: "MKE疲劳监测系统", value: "●" },
            { key: "MKB多次碰撞预防系统", value: "●" },
            { key: "ISOFIX儿童座椅固定装置", value: "●" },
            { key: "RKA智能胎压监测系统", value: "-" },
            { key: "TPMS Digital Display主动式智能胎压监测系统", value: "●" },
            { key: "前/后泊车雷达", value: "●" },
            { key: "RVC泊车后视影像系统", value: "-" },
            { key: "Top View 360°全景可视影像", value: "●" },
            { key: "开门预警系统", value: "●" },
          ],
        },
        {
          name: "功能",
          list: [
            { key: "Kessy智能（四门）无钥匙进入系统", value: "●" },
            { key: "Kessy智能一键启动系统", value: "●" },
            { key: "电动尾门", value: "●" },
            { key: "后备箱脚步感应开启", value: "●" },
            { key: "手机无线充电", value: "-" },
            { key: "10.25英寸全液晶数字仪表", value: "●" },
            { key: "手机映射（支持CarPlay等）", value: "●" },
            { key: "蓝牙手机免提系统", value: "●" },
            { key: "智能触控式三区自动恒温空调系统", value: "●" },
            { key: "Clean Air 3.0空气净化系统", value: "●" },
            { key: "前风挡加热", value: "O4" },
            { key: "前风挡清洗喷嘴加热", value: "O4" },
            { key: "高级智能平视显示系统wHUD", value: "-" },
            { key: "驾驶模式选择", value: "●" },
            { key: "DCC动态底盘控制系统", value: "-" },
            { key: "8扬声器高保真车载音响系统", value: "●" },
            { key: "Harman Kardon高级环绕音响带12扬声器", value: "-" },
          ],
        },
        {
          name: "车联网",
          list: [
            {
              key: "车联网 - 智联控车、智慧导航、智能语音、智享娱乐",
              value: "●",
            },
            {
              key: "CNS3.0智能车载导航信息娱乐系统：12英寸触摸彩屏",
              value: "●",
            },
            { key: "IQ. Drive", value: "" },
            { key: "GRA 定速巡航系统", value: "-" },
            { key: "ACC 3.0高级自适应巡航系统", value: "●" },
            {
              key: "Front Assist预碰撞安全系统（含AEB城市紧急制动）",
              value: "●",
            },
            { key: "PLA 3.0智能泊车系统", value: "●" },
            { key: "BSD 盲点监测系统", value: "●" },
            { key: "Lane Assist 车道保持系统", value: "●" },
            { key: "Travel Assist 一键式智能驾驶辅助系统", value: "●" },
            { key: "VZE交通标志识别", value: "●" },
            { key: "Pre-Crash预碰撞保护系统", value: "-" },
            { key: "RTA后方交通预警系统", value: "●" },
            { key: "IQ. Light", value: "" },
            { key: "全天候LED前大灯", value: "●" },
            { key: "大灯高度自动调节功能", value: "●" },
            { key: "高级全LED前大灯", value: "O3" },
            { key: "MDFS智能动态灯光辅助功能", value: "O3" },
            { key: "AFS大灯随动转向功能", value: "O3" },
            { key: "动态LED后转向灯", value: "●" },
          ],
        },
      ],
    },
    {
      model: "四驱 R-Line拓境版",
      price: "268900",
      paramList: [
        {
          name: "技术参数",
          list: [
            { key: "长×宽×高(mm)", value: "5,152 × 2,002 × 1,795" },
            { key: "轴距(mm)", value: "2,980" },
            { key: "后备厢容积(L)", value: "357 / 942 (7座880)" },
            { key: "油箱容积(L)", value: "74" },
            { key: "整备质量(kg)", value: "2160" },
            { key: "发动机型式", value: "直列四缸 / 涡轮增压" },
            { key: "发动机排量(L)", value: "1.984" },
            { key: "额定功率(kW/rpm)", value: "162 / 4,500-6,700" },
            { key: "最大扭矩(N·m/rpm)", value: "350 / 1,500-4,300" },
            { key: "变速箱型式", value: "7速DSG®湿式双离合自动变速器" },
            { key: "驱动形式", value: "四轮驱动" },
            { key: "最高车速(km/h)", value: "200" },
            { key: "0-100km/h加速(s)", value: "9.2" },
            { key: "综合工况油耗(L/100km)", value: "8.6" },
            {
              key: "悬架系统（前/后）",
              value: "前麦弗逊式独立悬架/后多连杆式独立悬架",
            },
            { key: "制动系统", value: "前/后通风盘式制动" },
            { key: "转向系统", value: "EPS电动随速助力转向" },
            { key: "排放标准", value: "国六排放标准" },
          ],
        },
        {
          name: "外饰",
          list: [
            { key: "LED日间行车灯", value: "●" },
            { key: "贯穿式LED尾灯", value: "●" },
            { key: "外饰氛围灯(格栅、门把手、侧标、行李架)", value: "●" },
            { key: "天使之翼迎宾光毯灯", value: "●" },
            { key: "前大灯感光自动开启", value: "●" },
            { key: "前大灯离回家功能", value: "●" },
            { key: "R-Line专属运动风格套件", value: "●" },
            { key: "Panorama大尺寸全景天窗", value: "●" },
            { key: "后排隐私玻璃", value: "●" },
            { key: "后排VSG降噪隐私玻璃", value: "-" },
            { key: "亮银色车顶行李架", value: "●" },
            { key: "鲨鱼鳍天线", value: "●" },
            {
              key: "多功能外后视镜（带LED转向灯、电动调节、加热功能）",
              value: "-",
            },
            {
              key: "多功能外后视镜（带LED转向灯、电动调节、加热功能、停车自动折叠）",
              value: "●",
            },
            {
              key: "多功能外后视镜（带LED转向灯、电动调节、加热功能、停车自动折叠、自动防眩目）",
              value: "-",
            },
            { key: "副司机侧外后视镜倒车辅助", value: "●" },
            { key: "20英寸Malana铝合金轮辋", value: "-" },
            { key: "21英寸Sapporo铝合金轮辋", value: "-" },
            { key: "21英寸铝合金R-Line造型轮辋", value: "●" },
            { key: "双色车身（黑色车顶）", value: "O8" },
            { key: "珠光白外饰漆", value: "O10" },
          ],
        },
        {
          name: "内饰 ",
          list: [
            {
              key: "智能触控内饰(灯光/视野控制区、中央控制区、顶棚控制区)",
              value: "●",
            },
            { key: "Shift by wire电子换档", value: "●" },
            { key: "皮革包覆软质内饰带真缝线（仪表板、门板）", value: "●" },
            { key: "前排中央扶手（高度及长度可调）", value: "●" },
            { key: "真皮多功能方向盘带换挡拨片", value: "●" },
            { key: "触控式方向盘", value: "●" },
            { key: "方向盘加热", value: "●" },
            { key: "6座（2-2-2布局）", value: "●" },
            { key: "7座（2-3-2布局）", value: "O1" },
            { key: "精致PVC+织物镶拼座椅", value: "-" },
            { key: "Vienna材质打孔真皮座椅", value: "-" },
            { key: "Vienna材质R-Line专属打孔真皮座椅", value: "●" },
            { key: "司机侧12向电动调节座椅(含4向腰托)", value: "●" },
            { key: "副司机侧12向电动调节座椅(含4向腰托)", value: "●" },
            { key: "司机侧座椅记忆功能", value: "●" },
            { key: "前排座椅加热", value: "●" },
            { key: "第二排座椅加热", value: "●" },
            { key: "前排座椅通风", value: "-" },
            { key: "第二排老板座椅高级通风按摩功能", value: "-" },
            { key: "第二排老板座椅带两侧独立扶手、带杯架", value: "●" },
            { key: "第二排座椅4/6可分体折叠", value: "O1" },
            { key: "第二排座椅中扶手（带弹出式杯架）", value: "O1" },
            { key: "第二排/第三排出风口", value: "●" },
            { key: "透光饰条", value: "-" },
            { key: "透光饰条R-Line风格", value: "●" },
            { key: "30色可调内饰氛围灯", value: "●" },
            { key: "顶棚USB充电插口（行车记录仪用）", value: "●" },
            { key: "前排USB插口x4", value: "●" },
            { key: "6座第二排USB充电插口x4 ", value: "●" },
            { key: "7座第二排USB充电插口x2 ", value: "O1" },
            { key: "第三排USB充电插口x2", value: "●" },
            { key: "R-Line金属运动脚踏板", value: "●" },
            { key: "金属迎宾踏板饰条", value: "-" },
            { key: "LED迎宾踏板饰条", value: "●" },
          ],
        },
        {
          name: "安全",
          list: [
            { key: "前排正面安全气囊x2", value: "●" },
            { key: "前排侧面安全气囊x2", value: "●" },
            { key: "前后贯穿式两侧头部安全气帘x2", value: "●" },
            { key: "司机侧膝部安全气囊x1", value: "●" },
            { key: "第二排侧面安全气囊x2", value: "●" },
            { key: "前排高度可调预紧式安全带", value: "●" },
            { key: "后座预紧式安全带", value: "●" },
            { key: "前排安全带未系提醒", value: "●" },
            { key: "第二排安全带未系提醒", value: "●" },
            { key: "Auto Hold 自动驻车", value: "●" },
            { key: "EPB 电子驻车", value: "●" },
            { key: "ESP车身稳定系统", value: "●" },
            { key: "HDC陡坡缓降系统", value: "●" },
            { key: "自动防眩内后视镜", value: "●" },
            { key: "智能雨量感应无骨雨刷", value: "●" },
            { key: "MKE疲劳监测系统", value: "●" },
            { key: "MKB多次碰撞预防系统", value: "●" },
            { key: "ISOFIX儿童座椅固定装置", value: "●" },
            { key: "RKA智能胎压监测系统", value: "-" },
            { key: "TPMS Digital Display主动式智能胎压监测系统", value: "●" },
            { key: "前/后泊车雷达", value: "●" },
            { key: "RVC泊车后视影像系统", value: "●" },
            { key: "Top View 360°全景可视影像", value: "-" },
            { key: "开门预警系统", value: "●" },
          ],
        },
        {
          name: "功能",
          list: [
            { key: "Kessy智能（四门）无钥匙进入系统", value: "●" },
            { key: "Kessy智能一键启动系统", value: "●" },
            { key: "电动尾门", value: "●" },
            { key: "后备箱脚步感应开启", value: "●" },
            { key: "手机无线充电", value: "-" },
            { key: "10.25英寸全液晶数字仪表", value: "●" },
            { key: "手机映射（支持CarPlay等）", value: "●" },
            { key: "蓝牙手机免提系统", value: "●" },
            { key: "智能触控式三区自动恒温空调系统", value: "●" },
            { key: "Clean Air 3.0空气净化系统", value: "●" },
            { key: "前风挡加热", value: "O5" },
            { key: "前风挡清洗喷嘴加热", value: "-" },
            { key: "高级智能平视显示系统wHUD", value: "-" },
            { key: "驾驶模式选择", value: "●" },
            { key: "DCC动态底盘控制系统", value: "-" },
            { key: "8扬声器高保真车载音响系统", value: "●" },
            { key: "Harman Kardon高级环绕音响带12扬声器", value: "-" },
          ],
        },
        {
          name: "车联网",
          list: [
            {
              key: "车联网 - 智联控车、智慧导航、智能语音、智享娱乐",
              value: "●",
            },
            {
              key: "CNS3.0智能车载导航信息娱乐系统：12英寸触摸彩屏",
              value: "●",
            },
            { key: "IQ. Drive", value: "" },
            { key: "GRA 定速巡航系统", value: "-" },
            { key: "ACC 3.0高级自适应巡航系统", value: "●" },
            {
              key: "Front Assist预碰撞安全系统（含AEB城市紧急制动）",
              value: "●",
            },
            { key: "PLA 3.0智能泊车系统", value: "●" },
            { key: "BSD 盲点监测系统", value: "●" },
            { key: "Lane Assist 车道保持系统", value: "●" },
            { key: "Travel Assist 一键式智能驾驶辅助系统", value: "●" },
            { key: "VZE交通标志识别", value: "●" },
            { key: "Pre-Crash预碰撞保护系统", value: "-" },
            { key: "RTA后方交通预警系统", value: "●" },
            { key: "IQ. Light", value: "" },
            { key: "全天候LED前大灯", value: "●" },
            { key: "大灯高度自动调节功能", value: "●" },
            { key: "高级全LED前大灯", value: "O3" },
            { key: "MDFS智能动态灯光辅助功能", value: "O3" },
            { key: "AFS大灯随动转向功能", value: "O3" },
            { key: "动态LED后转向灯", value: "●" },
          ],
        },
      ],
    },
    {
      model: "四驱 旗舰胜境版",
      price: "268900",
      paramList: [
        {
          name: "技术参数",
          list: [
            { key: "长×宽×高(mm)", value: "5,152 × 2,002 × 1,795" },
            { key: "轴距(mm)", value: "2,980" },
            { key: "后备厢容积(L)", value: "357 / 942 (7座880)" },
            { key: "油箱容积(L)", value: "74" },
            { key: "整备质量(kg)", value: "2160" },
            { key: "发动机型式", value: "直列四缸 / 涡轮增压" },
            { key: "发动机排量(L)", value: "1.984" },
            { key: "额定功率(kW/rpm)", value: "162 / 4,500-6,700" },
            { key: "最大扭矩(N·m/rpm)", value: "350 / 1,500-4,300" },
            { key: "变速箱型式", value: "7速DSG®湿式双离合自动变速器" },
            { key: "驱动形式", value: "四轮驱动" },
            { key: "最高车速(km/h)", value: "200" },
            { key: "0-100km/h加速(s)", value: "9.2" },
            { key: "综合工况油耗(L/100km)", value: "8.6" },
            {
              key: "悬架系统（前/后）",
              value: "前麦弗逊式独立悬架/后多连杆式独立悬架",
            },
            { key: "制动系统", value: "前/后通风盘式制动" },
            { key: "转向系统", value: "EPS电动随速助力转向" },
            { key: "排放标准", value: "国六排放标准" },
          ],
        },
        {
          name: "外饰",
          list: [
            { key: "LED日间行车灯", value: "●" },
            { key: "贯穿式LED尾灯", value: "●" },
            { key: "外饰氛围灯(格栅、门把手、侧标、行李架)", value: "●" },
            { key: "天使之翼迎宾光毯灯", value: "●" },
            { key: "前大灯感光自动开启", value: "●" },
            { key: "前大灯离回家功能", value: "●" },
            { key: "R-Line专属运动风格套件", value: "-" },
            { key: "Panorama大尺寸全景天窗", value: "●" },
            { key: "后排隐私玻璃", value: "-" },
            { key: "后排VSG降噪隐私玻璃", value: "●" },
            { key: "亮银色车顶行李架", value: "●" },
            { key: "鲨鱼鳍天线", value: "●" },
            {
              key: "多功能外后视镜（带LED转向灯、电动调节、加热功能）",
              value: "-",
            },
            {
              key: "多功能外后视镜（带LED转向灯、电动调节、加热功能、停车自动折叠）",
              value: "-",
            },
            {
              key: "多功能外后视镜（带LED转向灯、电动调节、加热功能、停车自动折叠、自动防眩目）",
              value: "●",
            },
            { key: "副司机侧外后视镜倒车辅助", value: "●" },
            { key: "20英寸Malana铝合金轮辋", value: "-" },
            { key: "21英寸Sapporo铝合金轮辋", value: "●" },
            { key: "21英寸铝合金R-Line造型轮辋", value: "-" },
            { key: "双色车身（黑色车顶）", value: "O8" },
            { key: "珠光白外饰漆", value: "O10" },
          ],
        },
        {
          name: "内饰 ",
          list: [
            {
              key: "智能触控内饰(灯光/视野控制区、中央控制区、顶棚控制区)",
              value: "●",
            },
            { key: "Shift by wire电子换档", value: "●" },
            { key: "皮革包覆软质内饰带真缝线（仪表板、门板）", value: "●" },
            { key: "前排中央扶手（高度及长度可调）", value: "●" },
            { key: "真皮多功能方向盘带换挡拨片", value: "●" },
            { key: "触控式方向盘", value: "-" },
            { key: "方向盘加热", value: "●" },
            { key: "6座（2-2-2布局）", value: "●" },
            { key: "7座（2-3-2布局）", value: "O1" },
            { key: "精致PVC+织物镶拼座椅", value: "-" },
            { key: "Vienna材质打孔真皮座椅", value: "●" },
            { key: "Vienna材质R-Line专属打孔真皮座椅", value: "-" },
            { key: "司机侧12向电动调节座椅(含4向腰托)", value: "●" },
            { key: "副司机侧12向电动调节座椅(含4向腰托)", value: "●" },
            { key: "司机侧座椅记忆功能", value: "●" },
            { key: "前排座椅加热", value: "●" },
            { key: "第二排座椅加热", value: "●" },
            { key: "前排座椅通风", value: "●" },
            { key: "第二排老板座椅高级通风按摩功能", value: "O7" },
            { key: "第二排老板座椅带两侧独立扶手、带杯架", value: "●" },
            { key: "第二排座椅4/6可分体折叠", value: "O1" },
            { key: "第二排座椅中扶手（带弹出式杯架）", value: "O1" },
            { key: "第二排/第三排出风口", value: "●" },
            { key: "透光饰条", value: "●" },
            { key: "透光饰条R-Line风格", value: "-" },
            { key: "30色可调内饰氛围灯", value: "●" },
            { key: "顶棚USB充电插口（行车记录仪用）", value: "●" },
            { key: "前排USB插口x4", value: "●" },
            { key: "6座第二排USB充电插口x4 ", value: "●" },
            { key: "7座第二排USB充电插口x2 ", value: "O1" },
            { key: "第三排USB充电插口x2", value: "●" },
            { key: "R-Line金属运动脚踏板", value: "-" },
            { key: "金属迎宾踏板饰条", value: "-" },
            { key: "LED迎宾踏板饰条", value: "●" },
          ],
        },
        {
          name: "安全",
          list: [
            { key: "前排正面安全气囊x2", value: "●" },
            { key: "前排侧面安全气囊x2", value: "●" },
            { key: "前后贯穿式两侧头部安全气帘x2", value: "●" },
            { key: "司机侧膝部安全气囊x1", value: "●" },
            { key: "第二排侧面安全气囊x2", value: "●" },
            { key: "前排高度可调预紧式安全带", value: "●" },
            { key: "后座预紧式安全带", value: "●" },
            { key: "前排安全带未系提醒", value: "●" },
            { key: "第二排安全带未系提醒", value: "●" },
            { key: "Auto Hold 自动驻车", value: "●" },
            { key: "EPB 电子驻车", value: "●" },
            { key: "ESP车身稳定系统", value: "●" },
            { key: "HDC陡坡缓降系统", value: "●" },
            { key: "自动防眩内后视镜", value: "●" },
            { key: "智能雨量感应无骨雨刷", value: "●" },
            { key: "MKE疲劳监测系统", value: "●" },
            { key: "MKB多次碰撞预防系统", value: "●" },
            { key: "ISOFIX儿童座椅固定装置", value: "●" },
            { key: "RKA智能胎压监测系统", value: "-" },
            { key: "TPMS Digital Display主动式智能胎压监测系统", value: "●" },
            { key: "前/后泊车雷达", value: "●" },
            { key: "RVC泊车后视影像系统", value: "-" },
            { key: "Top View 360°全景可视影像", value: "●" },
            { key: "开门预警系统", value: "●" },
          ],
        },
        {
          name: "功能",
          list: [
            { key: "Kessy智能（四门）无钥匙进入系统", value: "●" },
            { key: "Kessy智能一键启动系统", value: "●" },
            { key: "电动尾门", value: "●" },
            { key: "后备箱脚步感应开启", value: "●" },
            { key: "手机无线充电", value: "●" },
            { key: "10.25英寸全液晶数字仪表", value: "●" },
            { key: "手机映射（支持CarPlay等）", value: "●" },
            { key: "蓝牙手机免提系统", value: "●" },
            { key: "智能触控式三区自动恒温空调系统", value: "●" },
            { key: "Clean Air 3.0空气净化系统", value: "●" },
            { key: "前风挡加热", value: "●" },
            { key: "前风挡清洗喷嘴加热", value: "●" },
            { key: "高级智能平视显示系统wHUD", value: "O6" },
            { key: "驾驶模式选择", value: "●" },
            { key: "DCC动态底盘控制系统", value: "-" },
            { key: "8扬声器高保真车载音响系统", value: "-" },
            { key: "Harman Kardon高级环绕音响带12扬声器", value: "●" },
          ],
        },
        {
          name: "车联网",
          list: [
            {
              key: "车联网 - 智联控车、智慧导航、智能语音、智享娱乐",
              value: "●",
            },
            {
              key: "CNS3.0智能车载导航信息娱乐系统：12英寸触摸彩屏",
              value: "●",
            },
            { key: "IQ. Drive", value: "" },
            { key: "GRA 定速巡航系统", value: "-" },
            { key: "ACC 3.0高级自适应巡航系统", value: "●" },
            {
              key: "Front Assist预碰撞安全系统（含AEB城市紧急制动）",
              value: "●",
            },
            { key: "PLA 3.0智能泊车系统", value: "●" },
            { key: "BSD 盲点监测系统", value: "●" },
            { key: "Lane Assist 车道保持系统", value: "●" },
            { key: "Travel Assist 一键式智能驾驶辅助系统", value: "●" },
            { key: "VZE交通标志识别", value: "●" },
            { key: "Pre-Crash预碰撞保护系统", value: "●" },
            { key: "RTA后方交通预警系统", value: "●" },
            { key: "IQ. Light", value: "" },
            { key: "全天候LED前大灯", value: "-" },
            { key: "大灯高度自动调节功能", value: "●" },
            { key: "高级全LED前大灯", value: "●" },
            { key: "MDFS智能动态灯光辅助功能", value: "●" },
            { key: "AFS大灯随动转向功能", value: "●" },
            { key: "动态LED后转向灯", value: "●" },
          ],
        },
      ],
    },
    {
      model: "四驱 旗舰胜境版Pro",
      price: "268900",
      paramList: [
        {
          name: "技术参数",
          list: [
            { key: "长×宽×高(mm)", value: "5,152 × 2,002 × 1,795" },
            { key: "轴距(mm)", value: "2,980" },
            { key: "后备厢容积(L)", value: "357 / 942 (7座880)" },
            { key: "油箱容积(L)", value: "74" },
            { key: "整备质量(kg)", value: "2240" },
            { key: "发动机型式", value: "V型六缸 / 涡轮增压" },
            { key: "发动机排量(L)", value: "2.492" },
            { key: "额定功率(kW/rpm)", value: "220 / 5,250-6,250" },
            { key: "最大扭矩(N·m/rpm)", value: "500 / 2,750-3,500" },
            { key: "变速箱型式", value: "7速DSG®湿式双离合自动变速器" },
            { key: "驱动形式", value: "四轮驱动" },
            { key: "最高车速(km/h)", value: "200" },
            { key: "0-100km/h加速(s)", value: "8.2" },
            { key: "综合工况油耗(L/100km)", value: "9.7" },
            {
              key: "悬架系统（前/后）",
              value: "前麦弗逊式独立悬架/后多连杆式独立悬架",
            },
            { key: "制动系统", value: "前/后通风盘式制动" },
            { key: "转向系统", value: "EPS电动随速助力转向" },
            { key: "排放标准", value: "国六排放标准" },
          ],
        },
        {
          name: "外饰",
          list: [
            { key: "LED日间行车灯", value: "●" },
            { key: "贯穿式LED尾灯", value: "●" },
            { key: "外饰氛围灯(格栅、门把手、侧标、行李架)", value: "●" },
            { key: "天使之翼迎宾光毯灯", value: "●" },
            { key: "前大灯感光自动开启", value: "●" },
            { key: "前大灯离回家功能", value: "●" },
            { key: "R-Line专属运动风格套件", value: "-" },
            { key: "Panorama大尺寸全景天窗", value: "●" },
            { key: "后排隐私玻璃", value: "-" },
            { key: "后排VSG降噪隐私玻璃", value: "●" },
            { key: "亮银色车顶行李架", value: "●" },
            { key: "鲨鱼鳍天线", value: "●" },
            {
              key: "多功能外后视镜（带LED转向灯、电动调节、加热功能）",
              value: "-",
            },
            {
              key: "多功能外后视镜（带LED转向灯、电动调节、加热功能、停车自动折叠）",
              value: "-",
            },
            {
              key: "多功能外后视镜（带LED转向灯、电动调节、加热功能、停车自动折叠、自动防眩目）",
              value: "●",
            },
            { key: "副司机侧外后视镜倒车辅助", value: "●" },
            { key: "20英寸Malana铝合金轮辋", value: "-" },
            { key: "21英寸Sapporo铝合金轮辋", value: "-" },
            { key: "21英寸铝合金R-Line造型轮辋", value: "●" },
            { key: "双色车身（黑色车顶）", value: "O8" },
            { key: "珠光白外饰漆", value: "O10" },
          ],
        },
        {
          name: "内饰 ",
          list: [
            {
              key: "智能触控内饰(灯光/视野控制区、中央控制区、顶棚控制区)",
              value: "●",
            },
            { key: "Shift by wire电子换档", value: "●" },
            { key: "皮革包覆软质内饰带真缝线（仪表板、门板）", value: "●" },
            { key: "前排中央扶手（高度及长度可调）", value: "●" },
            { key: "真皮多功能方向盘带换挡拨片", value: "●" },
            { key: "触控式方向盘", value: "-" },
            { key: "方向盘加热", value: "●" },
            { key: "6座（2-2-2布局）", value: "●" },
            { key: "7座（2-3-2布局）", value: "O1" },
            { key: "精致PVC+织物镶拼座椅", value: "-" },
            { key: "Vienna材质打孔真皮座椅", value: "●" },
            { key: "Vienna材质R-Line专属打孔真皮座椅", value: "-" },
            { key: "司机侧12向电动调节座椅(含4向腰托)", value: "●" },
            { key: "副司机侧12向电动调节座椅(含4向腰托)", value: "●" },
            { key: "司机侧座椅记忆功能", value: "●" },
            { key: "前排座椅加热", value: "●" },
            { key: "第二排座椅加热", value: "●" },
            { key: "前排座椅通风", value: "●" },
            { key: "第二排老板座椅高级通风按摩功能", value: "O7" },
            { key: "第二排老板座椅带两侧独立扶手、带杯架", value: "●" },
            { key: "第二排座椅4/6可分体折叠", value: "O1" },
            { key: "第二排座椅中扶手（带弹出式杯架）", value: "O1" },
            { key: "第二排/第三排出风口", value: "●" },
            { key: "透光饰条", value: "●" },
            { key: "透光饰条R-Line风格", value: "-" },
            { key: "30色可调内饰氛围灯", value: "●" },
            { key: "顶棚USB充电插口（行车记录仪用）", value: "●" },
            { key: "前排USB插口x4", value: "●" },
            { key: "6座第二排USB充电插口x4 ", value: "●" },
            { key: "7座第二排USB充电插口x2 ", value: "O1" },
            { key: "第三排USB充电插口x2", value: "●" },
            { key: "R-Line金属运动脚踏板", value: "-" },
            { key: "金属迎宾踏板饰条", value: "-" },
            { key: "LED迎宾踏板饰条", value: "●" },
          ],
        },
        {
          name: "安全",
          list: [
            { key: "前排正面安全气囊x2", value: "●" },
            { key: "前排侧面安全气囊x2", value: "●" },
            { key: "前后贯穿式两侧头部安全气帘x2", value: "●" },
            { key: "司机侧膝部安全气囊x1", value: "●" },
            { key: "第二排侧面安全气囊x2", value: "●" },
            { key: "前排高度可调预紧式安全带", value: "●" },
            { key: "后座预紧式安全带", value: "●" },
            { key: "前排安全带未系提醒", value: "●" },
            { key: "第二排安全带未系提醒", value: "●" },
            { key: "Auto Hold 自动驻车", value: "●" },
            { key: "EPB 电子驻车", value: "●" },
            { key: "ESP车身稳定系统", value: "●" },
            { key: "HDC陡坡缓降系统", value: "●" },
            { key: "自动防眩内后视镜", value: "●" },
            { key: "智能雨量感应无骨雨刷", value: "●" },
            { key: "MKE疲劳监测系统", value: "●" },
            { key: "MKB多次碰撞预防系统", value: "●" },
            { key: "ISOFIX儿童座椅固定装置", value: "●" },
            { key: "RKA智能胎压监测系统", value: "-" },
            { key: "TPMS Digital Display主动式智能胎压监测系统", value: "●" },
            { key: "前/后泊车雷达", value: "●" },
            { key: "RVC泊车后视影像系统", value: "-" },
            { key: "Top View 360°全景可视影像", value: "●" },
            { key: "开门预警系统", value: "●" },
          ],
        },
        {
          name: "功能",
          list: [
            { key: "Kessy智能（四门）无钥匙进入系统", value: "●" },
            { key: "Kessy智能一键启动系统", value: "●" },
            { key: "电动尾门", value: "●" },
            { key: "后备箱脚步感应开启", value: "●" },
            { key: "手机无线充电", value: "●" },
            { key: "10.25英寸全液晶数字仪表", value: "●" },
            { key: "手机映射（支持CarPlay等）", value: "●" },
            { key: "蓝牙手机免提系统", value: "●" },
            { key: "智能触控式三区自动恒温空调系统", value: "●" },
            { key: "Clean Air 3.0空气净化系统", value: "●" },
            { key: "前风挡加热", value: "●" },
            { key: "前风挡清洗喷嘴加热", value: "●" },
            { key: "高级智能平视显示系统wHUD", value: "O6" },
            { key: "驾驶模式选择", value: "●" },
            { key: "DCC动态底盘控制系统", value: "●" },
            { key: "8扬声器高保真车载音响系统", value: "-" },
            { key: "Harman Kardon高级环绕音响带12扬声器", value: "●" },
          ],
        },
        {
          name: "车联网",
          list: [
            {
              key: "车联网 - 智联控车、智慧导航、智能语音、智享娱乐",
              value: "●",
            },
            {
              key: "CNS3.0智能车载导航信息娱乐系统：12英寸触摸彩屏",
              value: "●",
            },
            { key: "IQ. Drive", value: "" },
            { key: "GRA 定速巡航系统", value: "-" },
            { key: "ACC 3.0高级自适应巡航系统", value: "●" },
            {
              key: "Front Assist预碰撞安全系统（含AEB城市紧急制动）",
              value: "●",
            },
            { key: "PLA 3.0智能泊车系统", value: "●" },
            { key: "BSD 盲点监测系统", value: "●" },
            { key: "Lane Assist 车道保持系统", value: "●" },
            { key: "Travel Assist 一键式智能驾驶辅助系统", value: "●" },
            { key: "VZE交通标志识别", value: "●" },
            { key: "Pre-Crash预碰撞保护系统", value: "●" },
            { key: "RTA后方交通预警系统", value: "●" },
            { key: "IQ. Light", value: "" },
            { key: "全天候LED前大灯", value: "-" },
            { key: "大灯高度自动调节功能", value: "●" },
            { key: "高级全LED前大灯", value: "●" },
            { key: "MDFS智能动态灯光辅助功能", value: "●" },
            { key: "AFS大灯随动转向功能", value: "●" },
            { key: "动态LED后转向灯", value: "●" },
          ],
        },
      ],
    },
  ],
  mark: [
    "1. ● 标准配备          ○ 可选配备       - 不提供",
    {
      name: "2. 选装包定义：",
      list: [
        {
          key: "O1 七座选装包",
          item: [
            "7座（2-3-2布局）",
            "第二排座椅4/6可分体折叠",
            "第二排座椅中扶手（带弹出式杯架",
            "7座第二排USB充电插口(Type A x2 )",
          ],
        },
        {
          key: "O2  泊车辅助包 ",
          item: ["PLA 3.0智能泊车系统"],
        },
        {
          key: "O3  高级大灯包",
          item: [
            "高级全LED前大灯",
            "MDFS智能动态灯光辅助功能",
            "AFS大灯随动转向功能",
          ],
        },
        {
          key: "O4 冬季包",
          item: [
            "前风挡加热",
            "前风挡清洗喷嘴加热",
            "第二排座椅中扶手（带弹出式杯架",
            "方向盘加热（380TSI标配",
          ],
        },
        {
          key: "O5 风挡加热包",
          item: ["前风挡加热"],
        },
        {
          key: "O6 抬头显示包",
          item: ["高级智能平视显示系统wHUD"],
        },
        {
          key: "O7 高级老板座椅包",
          item: ["第二排老板座椅高级通风按摩功能"],
        },
        {
          key: "O8 双色车身（黑色车顶",
          item: [],
        },
      ],
    },
    " 3. 外饰颜色：锰石黑、极地白、珠光白、砾石灰、星耀金、阿拉比卡棕、星辰紫、昊空蓝",
  ],
};
